app/src/main/java/vn/mbm/phimp/me/Upload.java
app/src/main/java/vn/mbm/phimp/me/UploadProgress.java
app/src/main/java/vn/mbm/phimp/me/feedservice/FacebookActivity.java
app/src/main/res/values-de/google_maps_api.xml

Tested wordpress upload on phimpme wordpress test blog [https://github.com/fossasia/phimpme-wordpress](url)
According to me we should keep the implemented for wordpress as it is.It is good and will work for us.
**Screenshots of the app and wordpress.**

Wordpress upload working, tested on Phimpme blog

---

app/src/main/java/vn/mbm/phimp/me/newGallery.java

Closing of managed cursor leads to crash due to requery of the closed
cursor on activity resume. Removal of managed query usage fixes the crash.

Fix crash by removing managed query usage

---

app/src/main/res/layout/newgallery.xml

Adjusted the margins of the Home View [ #55 ] The new build in development had an additional margin which lifts the Gallery up. In this fix, I've corrected it!
Changes: 
- Margins were misaligned in the Home View gallery. They were set to 3dp!

fix: Margins of the GridView

---

app/src/main/java/vn/mbm/phimp/me/gallery3d/media/CropImage.java

Fixes issue #62 
Changes:
- Previously, both the original and edited images were saved separately causing a duplicate in the event of no editing has happened to the original image
- A way around this issue has been implemented by not saving the edited image if there were no edits to the picture.
- Original image and the edited image will be saved separately if there is an edit to the picture

fix: #62 Images taken from Camera shown twice in Gallery

---

app/src/main/java/vn/mbm/phimp/me/gallery3d/media/CropImage.java

Fixes issue : Saving cropped images
Changes:
- If someone crops the image, even by a pixel, it will be saved as an edited image

fix: Save cropped images

---

.travis.yml
app/src/androidTest/java/vn/mbm/phimp/me/CameraActivityTest.java
app/src/androidTest/java/vn/mbm/phimp/me/UploadActivityTest.java
app/src/main/AndroidManifest.xml

Fixes issue #77  : Implementation of UI tests with espresso
Changes: Implement Travis to run UI tests. Changed the UploadActivityTest a bit as it got changed in the recent PR. Removed the switchCamera button test as  it depends upon the no. of cameras in the device.

fix: Implements Travis to run Espresso UI tests

---

.travis.yml

The espresso tests were failing. This would resolve the issues and Travis would be up again.
Closes issue #121
Changes: wait for emulator option waits for the emulator but doesnot define a definite time, so I replaced it with  to sleep for a definite time.
**Since this was a high priority issue, I thought I would take it up**
Please review.

Turns Travis CI green. Closes #121

---

app/src/androidTest/java/vn/mbm/phimp/me/UploadActivityTest.java
app/src/main/java/vn/mbm/phimp/me/Upload.java

Fixes issue #180 _No Picture Selected :(_ label invisible after removing all the images
Changes: 
- Made _No Picture Selected :(_ label visible when the list is emptied
- Wrote Espresso tests to validate

fix: [ #180 ] No photos label will appear again!

---

app/src/main/java/vn/mbm/phimp/me/Upload.java

Changes: All icons used in app are of grey color. When we long press on upload grid 3 icons appear for deselecting, remove etc. They are of black color. I applied the same color filter to those icons.
<table>
<th>PREVIOUS</th><th>NOW</th>
<tr>
<td><img src="https://cloud.githubusercontent.com/assets/14369357/24084100/eede741e-0d09-11e7-8379-83b10ee7006c.png" width="320px">
</td>
<td><img src="https://cloud.githubusercontent.com/assets/14369357/24084098/deb3dc28-0d09-11e7-9a6e-b8b6f4e36d03.png" width="320px">
</td>
</tr>
</table>

Color Filter on icons in upload fragment

---

app/src/main/res/layout/cropimage.xml

In the Media Editor of Gallery, There is no use of having Original Filter in editors as the user, if wanted the same picture- Then user can cancel the edits(By Pressing Cancel Button).
@Abhi2424shek Please Review.

Removes Original Filter From Media Editor

---

app/src/main/java/vn/mbm/phimp/me/Camera2.java

Fixes issue #252 
Changes: Added a flag for indicating that the capturing process is under progress and clicks during that time will not have any effect.

Fixes Bug #252 : App getting crashed on double tapping capture button in camera 

---

app/src/main/java/vn/mbm/phimp/me/image/CropImage.java

Fixes issue #297 
Changes: 
At line 196 of cropimage class. There the image is getting downsampled by 4.
A scaledbitmap is being created only with those images whose dimensions after downsampling are not even. But this should be performed even if the dimensions are even. I changed that.

closes issue #297 Cropped image quality is very low

---

app/src/main/java/vn/mbm/phimp/me/gallery3d/media/CropImage.java

Fixes issue #321 
Changes: error was due to recycled bitmap so I removed bitmap.recycle() after image is rotated and also updated bitmap which is send to imagefilter class.

fixes issue #321 App crashes if user edit image in upload section

---

app/src/main/java/vn/mbm/phimp/me/gallery/PhimpMeGallery.java

Fixes issue #353 
Changes: 
image size is assigned by using its data when exifdata is not available

Closes issue #353 No size info of image when exif data unavailable 

---

app/src/main/java/vn/mbm/phimp/me/MapFragment.java

Fixes issue #363 
Changes: app was crashing because getactivity in LoadMarkers class(extends asynctask) was null. So I passed getactivity from fragment MapFragment to LoadMarkers. 

fixes issue #363 : App crashing on pressing map button

---

app/src/main/java/vn/mbm/phimp/me/Camera2.java
app/src/main/res/values/strings.xml

Fixes issue #359
Changes:
Added a check condition whether the phone's camera supports HDR mode.

closes issue #359 App crashing when HDR button is pressed in HDR unsupported devices

---

app/src/main/java/vn/mbm/phimp/me/Settings.java

Fixes issue #375 
Changes: on clicking save button after taking pic, phimpme activity start again and hence FEEDS_LOCAL_GALLERY variable(which is controling the state of checkbox) get reset. So I replace it by another variable which is changing only in settings activity.

 Fixes issue #375 state of checkbox is changing automatically

---

app/src/main/java/vn/mbm/phimp/me/newGallery.java

Fixes issue #382 
Changes:
- Stops image loading calls when the image list is full :)
> Not available

Closes #382 : Image loading stops at bottom

---

app/src/main/java/vn/mbm/phimp/me/Camera2.java
app/src/main/java/vn/mbm/phimp/me/gallery3d/media/CropImage.java

Fixes issue #404 App Crash in camera page
Changes: 
After multiple tries, finally found the reason. 
The Capture progress flag is getting reset before the next activity opens. There is a time gap between those steps. So if the capture button is pressed in that moment, the app is getting crashed.
So I moved the reset statement of progress flag to next opening activity and that worked fine.

fixes issue #404 App Crash in camera page

---

app/src/main/java/vn/mbm/phimp/me/gallery/PhimpMeGallery.java

Fixes issue #411 Removing redundant editing page. 
Changes: Redirected the editing page from image.CromImage.java to gallery.media.CropImage.java. This will bring a uniformity in the app.

Solved redundant image editing page. issue #411

---

app/src/main/java/vn/mbm/phimp/me/editor/editimage/EditImageActivity.java
app/src/main/java/vn/mbm/phimp/me/leafpic/data/Album.java

Fixes issue #518 Open edited Images after saving
Changes: Added intent to open SingleMediaActivity with new saved images paths. Made changes in Albums.java to avoid null pointer exceptions.

Open edit images after saving

---

app/src/main/java/vn/mbm/phimp/me/leafpic/data/providers/MediaStoreProvider.java

Fixes issue #537 Media count in album is always zero
Changes: Now the count is displayed according to no. of media in the album

Fixed media count issue

---

app/src/main/java/vn/mbm/phimp/me/leafpic/activities/SingleMediaActivity.java
app/src/main/java/vn/mbm/phimp/me/leafpic/data/Media.java

Fixes issue #523 
Changes: 
Removed the fix date option from dialog as it is not required.

removed the fix date button from details dialog

---

app/src/main/java/vn/mbm/phimp/me/leafpic/data/Album.java

Fixes issue #548 Filter by images option fixed
Changes: Now GIF's doesn't show along with images.

Filter by images fix

---

app/src/main/java/vn/mbm/phimp/me/leafpic/activities/LFMainActivity.java

Fixes issue #570 Toolbar does not update on swipe refresh
Changes: Added toolbar update function and finish edit mode function on post execution method of swipe refresh.

Toolbar update issue on swipe refresh fixed

---

app/src/main/java/vn/mbm/phimp/me/base/BaseActivity.java

Fixes issue #571 
**Actual Behaviour**
Activities are kept adding in activity stack. Suppose we open home->camera->accounts->camera->home->acccounts. There is a loop between the activities on pressing the back button.
**Changes:**
Clean the stack history. It can be check by performing multiple activities from the bottom navigation bar.

Activity Stack Maintain from bottom naigation bar

---

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java
app/src/main/java/org/fossasia/phimpme/leafpic/data/providers/StorageProvider.java
app/src/main/res/drawable/ic_photo_24dp.xml
app/src/main/res/menu/menu_albums.xml
app/src/main/res/values/strings.xml

Fixes issue #435 Toolbar option to switch to all photos.
Changes: 
1. Added all photos option.
2. Added click listeners for all photos to display it in singleMediaActivity.
3. Updated viewPager adapter with all media list.

Toolbar option to switch to all photos

---

app/build.gradle
app/src/main/java/org/fossasia/phimpme/opencamera/Preview/Preview.java
app/src/main/java/org/fossasia/phimpme/opencamera/UI/MainUI.java
app/src/main/java/org/fossasia/phimpme/opencamera/UI/PopupView.java
app/src/main/res/values/strings.xml
build.gradle

Fixes issue #598 
Changes: 
1. Now toggle button hides itself while taking picture.
2. Added long click listener to reset color effect.
3. Removed all color effects list from pop up view.
4. Add showcase view to show toggle button functionality.

Hide toggle button while taking picture and long press to reset color effects

---

app/src/main/java/org/fossasia/phimpme/editor/editimage/EditImageActivity.java
app/src/main/res/values/strings.xml

Fixes issue #604 
Changes: 
- If you capture a photo and open editor from next screen and press save&exit in editor -> Share image page opens.
- If you normally open editor by clicking edit in gallery and press save&exit in editor -> just the editor closes.
- If you press save&exit without editing, confirmation dialog appears.

Changed navigation flow to share image page from editor

---

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java

Fix #638 App crash on affixing images
Changes: Added function to resize bitmaps before affixing them

Fixes crash on affixing images

---

app/src/main/java/org/fossasia/phimpme/editor/editimage/EditImageActivity.java

Fix #670 
Changes: `mainImage` is not initialized properly, that causes `nullPointerException` on initiating the `EditImageActivity`

fix: crash fix on EditImageActivity

---

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java

Fix #680 
Changes: 1. Removed the delete button when the user switches to all photos mode and if its not in the edit mode.
2. Now media opens in singleMediaActivity from all photos mode.

Image doesn't load from all photos mode in SingleMediaActivity

---

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java

Fix #714 
Changes:
- Copy feature is enabled only when a photo is selected. 
- Copy feature disabled from the album view. 
- Move feature is enabled only when an album or a photo is selected

Hide copy and move item if no item is selected

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/phimpme/SharingActivity.java
app/src/main/res/values/strings.xml

Fix #747 
Changes: Fixed Facebook share image when the native app is not installed.

Fixed Facebook share image when native app is not installed.

---

app/src/main/java/org/fossasia/phimpme/SharingActivity.java
app/src/main/res/values/strings.xml
pdk/src/main/java/com/pinterest/android/pdk/PDKClient.java
pdk/src/main/java/com/pinterest/android/pdk/Utils.java

Fix #765 
Changes: Established Image share on Pinterest from SharingActivity.
Steps to reproduce:
->First sign into Pinterest from Accounts Activity. If loggedIn, logout and login again. 
->From sharingActivity add caption.
->Get BoardID: Go to the Pinterest.com-><Your board>->copy the URL of your board and paste it in https://www.nutt.net/how-do-i-get-pinterest-board-id/ . Copy the boardID. 
-> SharingActivity->Pinterest->Paste the BoardID->Post

Upload Image to Pinterest

---

app/src/main/java/org/fossasia/phimpme/SharingActivity.java
app/src/main/res/values/colors.xml
pdk/build.gradle

Fix #797 
Changes: Added color resources of all accounts for dark theme

Added dark theme colors for cells in sharing activity

---

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
app/src/main/java/org/fossasia/phimpme/accounts/AccountAdapter.java
app/src/main/res/layout/accounts_item_view.xml

Fix #826
Changes: Using `ThemeHelper` fixed the color of SignIn Switch 

fix: Account manager SignIn Switch color according to the theme

---

.gitignore
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/phimpme/SharingActivity.java
app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
app/src/main/java/org/fossasia/phimpme/sharetoflickr/FlickrActivity.java
app/src/main/java/org/fossasia/phimpme/sharetoflickr/FlickrHelper.java
app/src/main/java/org/fossasia/phimpme/sharetoflickr/tasks/GetOAuthTokenTask.java
app/src/main/java/org/fossasia/phimpme/sharetoflickr/tasks/OAuthTask.java
app/src/main/java/org/fossasia/phimpme/sharetoflickr/tasks/UploadPhotoTask.java

Fix #809 
Changes: Added functions and tasks for authenticating and sharing image to flickr.
Testing:
First add the API token and Secret token in FlickrHelper class. then build the application.
Add account by clicking Flickr item in account activity.
Then click Flickr in sharing activity.

Added share image to Flickr feature

---

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
app/src/main/java/org/fossasia/phimpme/accounts/AccountAdapter.java
app/src/main/java/org/fossasia/phimpme/accounts/AccountContract.java
app/src/main/java/org/fossasia/phimpme/accounts/AccountPresenter.java
app/src/main/java/org/fossasia/phimpme/data/local/AccountDatabase.java
app/src/main/java/org/fossasia/phimpme/utilities/Constants.java

Fix #837 
Changes: 
Added enum in `AccountDatabase` Model class
Change the implementation of creating realm object and used AccountName type parameter 
Now everything works with the name, no indexing based work which is highly error prone and not a best practive.

Using enum types in AccountDatabase model class to avoid using indexing of an array

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/phimpme/MyApplication.java
build.gradle

Fix #829 
Changes:
Added crashlytics instead of firebase because Firebase also promotes to use crashlytics.
Also added all other 4 members in fabric portal.

Added Crashyltics for crash reporting

---

app/src/main/java/org/fossasia/phimpme/SharingActivity.java
app/src/main/java/org/fossasia/phimpme/accounts/AccountContract.java
app/src/main/res/values/strings.xml

Fix #815 
Changes: In sharing Activity checks if the user is logged In to the Pinterest or not. If the user is not logged In snack-bar pops to redirect the user to Accounts Activity to log in.

Checking if logged in to Pinterest or not

---

app/src/main/java/org/fossasia/phimpme/share/ShareAdapter.java
app/src/main/res/layout/share_item_view.xml
app/src/main/res/values/colors.xml

Fix #873 
Changes: Generated the color resources in the loop for light as well as dark theme and applied on the text and icons in the `ShareAdapter`

added text color and colorfilter on images in SharingActivity

---

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
app/src/main/java/org/fossasia/phimpme/utilities/NotificationHandler.java

Fix #893 
Changes: Added progress listener to the box image uploads.
To test this enter keys in constants and log in with box credentials.
Then upload image on box from share activity.

Added real time upload progress for Box uploads

---

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java

Fix #896 
Changes: Removed the exclude album option from photosmode context menu in gallery.

Removed exclude from photosview mode

---

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java
app/src/main/java/org/fossasia/phimpme/editor/utils/FileUtil.java
app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java
app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java
app/src/main/java/org/fossasia/phimpme/opencamera/Camera/PhotoActivity.java
app/src/main/res/layout/activity_photo.xml
app/src/main/res/values/strings.xml

Fix #876 
Changes:
- removed unnecessary static start methods
- changed startactivityforresult to startactivity(result is not used anywhere)
- fixed empty white images being created when a new photo is captured and shared without editing.

changed way of starting photoactivity and editimage activity

---

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
app/src/main/java/org/fossasia/phimpme/accounts/AccountAdapter.java
app/src/main/java/org/fossasia/phimpme/data/local/AccountDatabase.java
app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
app/src/main/java/org/fossasia/phimpme/utilities/Constants.java
app/src/main/java/org/fossasia/phimpme/utilities/Utils.java
app/src/main/res/values/strings.xml

Fix #894 
Changes:
Because we cannot google plus api. The only way to use google plus domain API and it is paid.

Google plus & Instagram handled correctly in sharing activity

---

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java

Fix #914 
Changes: Added condition to hide option if the selected photos count not equals to one.

Hidden set as album preview option if no image selected

---

app/src/androidTest/java/org/fossasia/phimpme/leafpic/activities/HomeScreenTest.java
app/src/androidTest/java/org/fossasia/phimpme/leafpic/activities/SettingsActivityTest.java
app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/SliderFragment.java
app/src/main/jni/enhance.cpp
app/src/main/res/layout/activity_image_edit.xml

Fix #972 
Changes: 
Progress dialog was large and the message was also not visible as it appears only for a fraction of second. 
It looks better after replacing it with a progressbar.
Also fixed an error while adjusting saturation

changed progress dialog to progress bar when applying edits

---

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java

Fix #998
Fix #1005 
Changes: Fixed the issue to open keyboard when trying to add a caption and added conditions to display the already added captions if any.

fix: keyboard opens at once on clicking the add caption button

---

app/src/main/java/org/fossasia/phimpme/opencamera/UI/DrawPreview.java
app/src/main/res/xml/preferences.xml

Fix #997 
Changes: 
Removed the location logo which is overlapping on the toggle button in camera
Also removed the unnecessay require location to capture option in camera settings

Removed location logo overlapping on toggle in camera

---

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java

Fix #1021
Changes: handle exception of not having camera permissions, while triggering through voice.

fix getting runtime permissions on first time app open through voice control

---

app/src/main/AndroidManifest.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/shortcuts.xml

Fix #1037 
Changes: Added static shortcuts to open gallery, camera or accounts on long clicking the app icon
Note - Works for Android versions greater than 7.0 (Nougat)

Added app shortcuts to directly open camera, gallery or accounts from launcher

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/PaintFragment.java
app/src/main/res/values/strings.xml

Fix #1042 
Changes: Changed the color palette used in the Paint Fragment. The previous color palette for confusing and it was hard for any normal user to choose the desired color. 
It maintains the uniformity of the application.
Steps To Reproduce-> Edit Image Activity->Write->Paint->More

Changed the colour palette used in the Paint Fragment

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fix #1061 
Changes: Now the toolbar image count changes on deleting a photo from the Albums mode

Fix: Toolbar count changes on deleting a picture from albums mode

---

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java

Fix #1058 
Changes: Use the AlertDialogHelper class to get the properly formatted dialog box

Fix #1058 - Improve formatting of Unsaved changes dialog box.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fix #1063 
Changes: Fixed the app crash on opening photos from the all photos list. Getting the image description from the getAlbums function was causing a null pointer exception.

Fix: App crash on opening photos from the all photos list

---

app/build.gradle
app/src/main/java/org/fossasia/phimpme/opencamera/Preview/Preview.java

Fix #1074 
Changes: Since we are using MaterialShowCaseView there is no need for ShowcaseView in the Gradle.

Removed ShowcaseView from the gradle

---

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java
app/src/main/res/layout/content_accounts.xml
app/src/main/res/layout/upload_history_activity.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Added icon to show empty userhistory

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java

Fix #1076 
Changes: Now switches are set as disabled when the access by password option is turned off

Enhancement in security activity

---

README.md

Fix #1069
Changes: Added Developer's image, github and twitter link in section
Preview : https://github.com/pa1pal/phimpme-android/tree/readme

added image and twitter, github link in readme developer category

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fix #1087 
Changes: Add this line after :  getAlbum().moveCurrentMedia(getApplicationContext(), path);
getSupportActionBar().setTitle((getAlbum().getCurrentMediaIndex() + 1) + " " + getString(R.string.of) + " " + getAlbum().getMedia().size());
The toolbar info now updates when the image is moved

Fix #1087 - Update toolbar information when image is moved

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
app/src/main/res/values/strings.xml

Fix #1007 
Changes: Fixed image upload on Facebook due to an inactive account. 
Currently, Image upload is possible only for Developers. Once Facebook Reviews the app, public users can upload the image on Facebook.

Fixed Facebook Upload Image

---

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
app/src/main/res/menu/menu_accounts_activity.xml

Fix #1095 
Changes: Add Settings to menu of AccountActivity and add intent to launch settings from there

Fix #1095 - Add SettingsActivity intent in AccountActivity in menu

---

app/src/main/res/layout/activity_leafpic.xml
app/src/main/res/layout/toolbar.xml

Fix #1098 
Changes: Toolbar will now disappear on scrolling down and appear on scrolling up when image folders or images are viewed.

Fix:toolbar issue on scrolling

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java

Fix #1099 
Changes: The keyboard is automatically opened when password is prompted for entering Security section.

Fix #1099 - Open keyboard when password is prompted 

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1105 
Changes: Correct toolbar titles are displayed now.

Fix #1105 -display correct toolbar title

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/AboutActivity.java

Fix #1109 
Changes: Fossasia contributors link is now working

Fix #1109 - add Fossasia contributors link

---

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/PhotoActivity.java

Fix #1135
Changes: Use the same strategy as used in ImageAdapter to load the image quickly.

Fix #1135 - Preview image loads quickly

---

app/src/main/res/layout/activity_leafpic.xml

Fix #1121 
Changes: Add layout_behaviour to the main content.

Fix #1121 - Toolbar does not overlap with main content.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1155 Navigation Icon now on selecting album/image(s) is a X(clear).
Changes: Changed check to clear

Fix #1155 - Fix Navigation Icon

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1146 - Action bar bug fixed
Changes: Action Bar is now not scrolling up while selecting an album or image(Added two methods appBarOverlay and clearOverlay)

Fix #1146 - App bar not coming on image selection

---

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/data/HandlingAlbums.java

Fix #1153 
Changes: 
Earlier 2 types of warnings were issued:
1) Unchecked Cast: This was caused because a variable ("o") of the type **Object** was cast into an ArrayList<String> and Android Studio isn't sure whether the casting is safe or not and so it'll always give a warning .So the only way was to suppress warnings by using **SuppressWarning** annotation at the 2 places from where the error was popping up.
2) In the second type the issue was that the code wasn't using **Generics** . So **List** type variable  had to be written as List (String) otherwise if a List object of type other than String would be added , it would give a compile time error.

Minimized the build warnings to zero

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1156 Toolbar title is now as expected on clicking navigation icon.
Changes
Earlier On Clicking navigation icon after selecting album(s), toolbar title changes to All. Now it is working as expected.

Fix #1156 - Clicking navigation icon after album selection, now doesn't change toolbar title.

---

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/MyTileService.java
app/src/main/java/org/fossasia/phimpme/opencamera/Camera/MyTileServiceFrontCamera.java
app/src/main/java/org/fossasia/phimpme/opencamera/Camera/MyTileServiceVideo.java

Fix #1169 Navigation Shade, now auto close on tapping on quick setting tile(Camera/Selfie/Video).
Changes: Before navigation shade was not collapsing on by its own, now it is
Same is with the selfie and video tile.

Fix #1169 - Tapping on tile now auto collapse the navigation shade

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/res/layout/activity_leafpic.xml
app/src/main/res/values/strings.xml

Fix #1165 
Changes: Change to CoordinatorLayout in activity_leafpic.xml so that Snackbar is displayed properly

Fix #1165 - Display snackbar when media is moved and copied.

---

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java
app/src/main/res/values/strings.xml

Fix #1190 Prompting dialog to share the image.
Changes: Earlier on clicking save, the user was redirected to share the image, now he is asked first by using a dialog.
Please review @anantprsd5 @mohitmanuja @vinaysajjanapu

Fix #1190 - Prompting dialog for sharing image

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/AddTextFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/CropFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/PaintFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/RecyclerMenuFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/RotateFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/SliderFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/StickersFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/TwoItemFragment.java
app/src/main/res/layout/editor_iconitem.xml

Fix #1167 
Changes: Highlight the effect under consideration.

Fix #1167 -Highlight the sub-edit option when selected.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java

**Fix #1143**
**Changes:**
*Modifies a simple boolean logic  
Now app starts with colored nav bar and in settings, colored-nav-bar option is also enabled.*  
**Screenshots for the change:**
>Nav color is blue and option is also enabled by default when app start for the very first time
>Disabling nav bar color option still works fine

Fix: #1143 Navigation bar color issue

---

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java
app/src/main/res/values/strings.xml

Fix #1206 
Changes: Earlier on saving an image, without editing dialog appears, with a title, "discard changes" though no changes were made, now its title is "No Changes Made!"

Fix #1206 - Dialog title

---

.travis.yml

Fix #1204 
Changes: Add to .travis.yml
./gradlew assembleRelease

Fix #1204-Generate Unsigned release APK.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1215 
Changes: Keyboard now comes automatically when user clicks on a password protected hidden folders

Fix #1215 - Keyboard issue with Hidden Folders

---

index.html

Fix #1219 
Changes: Used phimpme logo as the page favicon.

Fixes #1219, Use phimpme logo as gh-page favicon

---

_static/fossasia.css
index.html

Fix #1218 
Changes: 
Corrected badges orientation in gh-page.

Fixes #1218, corrected badges orientation

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1222 
Changes: BottomNavigationBar is hidden when the user selects albums or photos and becomes again visible when the user presses the back button ,deselects all the selected media or clicks on any menu item.

Fixes #1222 Bottom navbar hides when albums or photos are selected

---

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java

Fix #1266 
Changes: Hint visible along with underline below text property.

Fix #1266-Hint visible along with underline below text property

---

app/src/main/java/org/fossasia/phimpme/gallery/data/MetadataItem.java

Fix #1235 
Changes: Details dialog will show resolution in Megapixels also

Fix #1235 resolution is given in megapixels too

---

app/src/main/java/org/fossasia/phimpme/gallery/SelectAlbumBottomSheet.java
app/src/main/res/values/strings.xml

Fix #1228 
Changes: Folders with no name or folders which already exist will not be created instead the user will get a toast message

Fixes #1228 create new folder will not make folders with no name

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1212
Changes: Animation to app bar added, now when the user selects a photo/album, app bar is animated.
@vinaysajjanapu @anantprsd5 @mohitmanuja 
Please review.

Fix #1212 - Add appbar animation

---

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java

Fix #1248 
Changes: Add it to the switch block

Fix #1248 - Fix sharing to messenger.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1277
Changes: When any item(s) is selected, then swipe to refresh is disabled, and as soon as the total item selected = 0, swipeRefreshLayout is enabled again.

Fixes #1277 Disable swipeRefreshLayout on item selection

---

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java

Fix #1279 
Changes: Add option to save in the discard changes warning dialog

Fix #1279 - Add save option to discard changes dialog.

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/RecyclerMenuFragment.java

Fix #1237 
Changes: 
Earlier the app was crashing after we selected a certain filter and then without applying it selected another filter by scrolling the horizontal recycler view to the right.This problem had arised because of the use of findViewHolderForAdapterPosition() returned null as the colour Transparent was being applied on a viewholder which wasn't present on the screen after scrolling.

Fix#1237 App doesn't crash on selecting filter

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/PaintFragment.java
app/src/main/java/org/fossasia/phimpme/editor/view/CustomPaintView.java

Fix #1265
Changes:
The canvas size which was too large earlier is now clipped to the photo on which editing is to be done.
As shown in the image shown below , it is still in editing mode and the paint doesn't go outside the image.
@mohitmanuja @anantprsd5 Kindly review the P.R Thankyou!

Fix #1265 Paint doesn't cross the photo boundary

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/res/values/strings.xml

Fix #1307 
Changes: There will be a snackbar message if the album name is already same and internally it will not make a new file. Now if you rename phimp.me camera with the same name and click a new picture , it will get added to the same folder.

Fix #1307 check if the album name is same

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1385 
Changes:if we deselect an album by long pressing it ,the bottom navigation bar does not get hidden

Fix #1385 bottom nav bar is now visible when no album is selected

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/data/Album.java

Fix #1372 
Changes: Bottom Navigation View remains hidden when photos are selected and is visible when all photos are deselected.

Fixes #1372 Bottom nav hidden

---

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/util/AlertDialogsHelper.java
app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java

Fix #1287 
Changes: Made a method in AlertDialogsHelper to set input color to all the buttons.

Fix #1287 - Give color to button text.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fix #1406 
Changes:When details of the image are opened , on clicking the back button the user returns to the image instead going back to LFMainActivity

Fix #1406 back button takes back to image

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1405 
Changes: app doesn't crash when an album is deleted

Fix #1405 app does not crash on delete

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1284 
Changes: Earlier when images were shared after long pressing images in the LFMainActivity , upload history didn't show the changes . Now I am storing the images in Realm and they are getting displayed in upload history.
@mohitmanuja @anantprsd5 Kindly Review!

Fix:1284 Items now visible in Upload History

---

app/src/main/java/org/fossasia/phimpme/base/BaseActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/utilities/SnackBarHandler.java
app/src/main/res/layout/activity_leafpic.xml
app/src/main/res/layout/element_bottom_navigation.xml

Fix #1322 
Changes: Add methods in the base activity to animate fade in and fade out for bottom navigation bar.
Also fixed the toolbar scrolling issue.
Add new method in snackback handler for a snackbar with bottom margin

Fix #1322 - Add animation for bottom navigation bar visibility changes.

---

app/src/main/java/org/fossasia/phimpme/gallery/data/Album.java

Fix #1370 
Changes: Add `previewPath` and `isPreviewSelected` properties to **Album**.
Whenever an image is moved or deleted check if it is the preview image. If yes then clear the preview for the album.
Actually the whole sequence cannot be properly covered in a GIF so how should I share the screen recording?

Fix #1370 - Moving or deleting preview image is reflected in the album.

---

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java

Fix #1412 
Changes: Now the latest changes can be seen at the top of upload history.
Take a look at the time!

Fix #1412: Upload History reversed

---

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java

Fix #1396 
Changes: The boolean **triedUploading** was set to false while sharing via whatsapp . If the result status after sharing was RESULT_OK then **triedUploading** was set to true.
@anantprsd5 @mohitmanuja Kindly review!

Fix#1396 Sharing via Whatsapp bug

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1411
Changes: affix dialog has coloured buttons

Fix #1411 affix dialog has coloured buttons

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1424 
Changes: Correct snackbar message is displayed when an album is renamed with the same name(after opening an album)

Fix #1424 correct snackbar message is displayed on renaming

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/utilities/SnackBarHandler.java

Fix #1421 
Changes: Color of action button of snackbar changed to Accent color.

Fixes 1421 Action button color changed to accent color

---

app/src/main/java/org/fossasia/phimpme/gallery/SelectAlbumBottomSheet.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java

Fix #1432 
Changes: Cancel button is added to the dialog. Now on opening any of the dialoges the Ok button will appear disabled at first and will be enabled only if the user updates the text in the edittext.

Fix #1432-Added cancel button in the create folder dialog

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1431 
Changes: snackbar messages are now visible in LFMainActivity

Fix #1431 snackbar messages are now visible

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1371 
Changes: Clear selection when album is pinned or un-pinned

Fix #1371 - Pinning or Unpinning album clears selection mode.

---

app/build.gradle
app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/util/BlurImageUtil.java
app/src/main/res/layout/image_description.xml

Fix #1387 
Changes: Use blurred version of current image as the background

Fix #1387 - Improve UI of details screen.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fix #1487 
Changes: 
Added a check before opening EditImageActivity.
Now, a snackbar is shown with a message "Invalid Image".

Fix#1487 Editing gif doesn't crash the app

---

app/src/main/res/layout/activity_about.xml

Fixes https://github.com/fossasia/phimpme-android/issues/1493
Screenshots :

Rectify the text orientation in the about page of the App

---

app/src/main/res/layout/activity_leafpic.xml

Fix #1491 
Changes: Set ` clipToPadding = false ` for photos recycler view 

Fix #1491 - Bottom navbar animation works fine for photos.

---

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
app/src/main/java/org/fossasia/phimpme/accounts/AccountAdapter.java

Fix #1490 
Changes: Make the cards theme based with proper background colour.

Fix #1490 - Accounts activity cards are now theme based.

---

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java
app/src/main/java/org/fossasia/phimpme/opencamera/Camera/MyPreferenceFragment.java
app/src/main/res/xml/preferences.xml

Fix #1278  Pausing after click toggle option made working.
Changes: The value for the pausing after a click is set to true, that means the pic will always be shown after the click.
Now if the value is changed, the image is saved directly without pausing.
@mohitmanuja @anantprsd5 @mayank8318 @aditya98ak Review and merge!

Fix #1278: Pausing after click working

---

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java

Fix #1494 
Changes: Give background color according to theme.

Fix #1494 - Image is now visible in all the themes.

---

app/src/main/res/layout/card_album.xml

Fix #1501 
Changes: Change `layout_height` from `match_parent` to `wrap_content`

Fix #1501 - Fix album card glitch for horizontal orientation.

---

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java
app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistoryAdapter.java
app/src/main/res/layout/upload_history_activity.xml
app/src/main/res/layout/upload_history_item_view.xml

Fix #1468 
Changes: The items are displayed in GridLayout with spancount 2, enlarged center-croped version of the shared image is displayed, spacing between the attributes is properly managed.

Fix #1468-Upload History UI enhanced.

---

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java
app/src/main/java/org/fossasia/phimpme/opencamera/Preview/Preview.java
app/src/main/java/org/fossasia/phimpme/opencamera/UI/MainUI.java
app/src/main/res/layout/activity_camera.xml

Closes #1436
The status and navigation bar are now hidden inside the camera activity.

fixes #1436 Hides status and navigation bar in camera activity

---

app/src/main/java/org/fossasia/phimpme/opencamera/Preview/Preview.java

Fix #1435 
Fixed issue with the overflow menu in the ```CameraActivity```. On clicking on an already selected option, the value is deactivated and the default value is automatically selected. For eg. - On selecting torch after torch is already active, switches the torch off and set the flash to off automatically.
Added this feature for both focus and flash options.

fixes #1435 fixed issue with the overflow menu in the camera activity

---

app/src/main/res/layout/dialog_description.xml

Fix #1529 
Changes:
I modified the editText of the description dialog box.
The editText now increases in height downwards as more text is entered. This way the text is not hidden and user can see entire text entered.

Fix #1529 . Description dialog editText now extends downwards as text is entered.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
app/src/main/res/layout/activity_drawer.xml
app/src/main/res/values/strings.xml

Second step for issue #1289 
Changes: Favourite collection photos displayed to the users, actions such as sharing, deletion etc can be performed on them.

Fix #1289-Favourite collection photos displayed to the users.

---

app/src/main/res/layout/toolbar.xml
app/src/main/res/values/styles.xml

Fix #1535
Changes: Fix toolbar text size for all orientations.

Fix #1535 - Fix the toolbar text size to default size.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1583 
Earlier app was crashing on renaming the album. Instead of using only getColor( ) , ContextCompat(context,color) should be used.

App doesn't crash on renaming album

---

app/src/main/java/org/fossasia/phimpme/MyApplication.java

Fix #1550
Changes:  android **below API 23** does not check for file uri exposure while above API 24 device checks this.So we can disable it by setting a new [VmPolicy](https://stackoverflow.com/a/40674771
).

Fixes #1550 App stop working when pressing "Use as" in selected picture

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1586 
Changes: option to clear album cover is visible only when we open an album whose cover has been changed. It is not visible in the all photos mode

Fix #1586 clear preview is  visible only when we open an album

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/res/layout/dialog_album_detail.xml

Fix #1568 
Changes: The updated list is displayed in the same order after performing delete action as it was before.

Fix #1568-All photos delete issue fixed.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fix #1581 
Changes: All snackBar messages are now visible in the singleMedia Activity

Fix #1581 snackbar messages are now visible

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/res/layout/activity_leafpic.xml

Fix #1598 
Changes: Removed redundant `android:alpha="0.7"` as it was being done programmatically in the activity and unused import statements.The colour of fab is now according to the accent colour

Fix #1598 colour of fab is according to the accent colour

---

app/src/main/java/org/fossasia/phimpme/gallery/adapters/AlbumsAdapter.java
app/src/main/res/drawable/pin_black.xml
app/src/main/res/drawable/pin_white.xml
app/src/main/res/layout/card_album.xml

Fix #1601 
Changes:The pinned to top icon is now visible in the dark mode as well.

Fix#1601: Pinned icon in dark mode

---

app/src/main/jni/enhance.cpp
app/src/main/jni/enhance.h
app/src/main/jni/main_processing.cpp
app/src/main/res/values/arrays.xml

Fixed #1644  
The C++ native filter files had to be changed and some additions had to be made in them so that the blur feature was incorporated properly. 
Earlier there was no feature to blur the images.
Before : 
After :

Added the feature to blur images

---

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/ImageSaver.java

Fixed #1651
Changes: Actually on resetting, all the saved values in the shared preference(SP) are removed. So saved that value("burst_mode") again in the SP.The value is always 1.

Fixed #1651 app doesn't crash on clicking camera button after resetting

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
app/src/main/res/layout/image_description.xml

Fixed #1523 
Changes: Image detail attributes visible properly for all the images, the description view layout is modified from the blur background layout to the theme based background layout.

Fix #1523-Image details attributes properly visible for all the images.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fix #1560
Changes: resize the grid layout easily using pinch gesture.(this feature is used in Google Photos)
[Doc](http://wiki.workassis.com/pinch-zoom-in-recycler-view/)

Fix #1560 Resize Grid layout[Album+media list] using pinch gesture

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/data/Album.java
app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java
app/src/main/res/layout/activity_security_layout.xml
app/src/main/res/layout/dialog_security_folder.xml
app/src/main/res/layout/secure_folder_dialog_item_view.xml
app/src/main/res/layout/select_folder_bottom_sheet_item.xml
app/src/main/res/values/preferences-key.xml

Fix #1558 
Changes: On enabling the security for albums(present in the local folders) through the security option in settings a dialog box pops up where the user can choose the albums which he/she wants to password secure, and after that for performing any operation on the chosen albums, entering the password is required.

Fix #1558-Added option to password secure particular folders.

---

app/src/main/java/org/fossasia/phimpme/gallery/adapters/AlbumsAdapter.java
app/src/main/res/drawable/ic_sd_storage_white_24dp.xml
app/src/main/res/layout/card_album.xml

Fixed #1661 
Changes: Select appropriate icon to display.

Fix #1661 - SD card icon is selected according to the theme.

---

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java

Fixed #1720
Changes: The reason was that the toolbar color for Account activity was only set in onCreate() method , so when the primary color is changed, the toolbar color remains the same.

Fixed  #1720 The toolbar of accounts activity is changing according to the primary color.

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/AddTextFragment.java

Fixed #1697 
Changes: Edittext gains focus on the opening up of the AddText fragment, softkeyboard pops up automatically.

Fix #1697-Adding text to a photo edittext isuue resloved.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java

Fixed #1700
Changes: When you install the activity for the first time, open the settings and click on Camera option you will be directed to camera activity. Now if press back you will taken back to the dialog box i.e the settings activity. So added finish() to destroy the settings activity so that Gallery opens on pressing back. Same event happens when you reset your settings and click on the Camera option in settings.

Fixed  #1700 on pressing back gallery is shown

---

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java

Fixed #1735:Whatsapp shared items not showing in upload history
Changes:Edited Sharingactivity , did by sending value from whatsappsharing function

#1735 Fixed-Whatsapp sharing error

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #1730
Changes: The text colour of the delete button changes according to the change in accent colour, the delete button is disabled if there is no description saved for the image. The text colour of the update and delete button is changed to the same colour when the buttons are disabled.

Fix #1730-Description dialog issue resolved.

---

app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java

Fixed #1766 
Changes: Password is entered in the hidden mode at first. The cursor is set to the end of the text when checking/unchecking the checkbox to hide/show password.

Fix #1766-Issue in the insert password dialog resolved.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixes #1849- "Hidden Folders" remains highlighted even when local folders are opened in navigation drawer.
Changes: 3 lines added in LFMainAcitivity.java to change the highlighted option back to local folders when gallery button in bottom navigation drawer is pressed.
Before change(when local folders are opened)
After change(when local folders are opened)

Fixes #1849 "Hidden Folders" remains highlighted even when local folders are opened in navigation drawer.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #1848 
Changes: Description option visible for favourites, the description of an image can be changed in the favourites collection and the change is reflected to the image present in its parent album.

Fix #1848-Description option visible for favourite collection photos.

---

app/src/main/res/values/arrays.xml

Fixed #1781 
Changes: 
Changed burst mode options from off,2x,3x,4x,5x,10x,unlimited  to  off,5x,10x,25x,40x,unlimited-->99x.

Fixed #1781 - Unlimited Burst Mode now working in Camera.

---

app/src/main/java/org/fossasia/phimpme/opencamera/Preview/Preview.java

Fixed #1859 
Changes: Check for null filter list(devices which don't support filters).

Fix #1859 - App doesn't crash on long pressing toggle filter.

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/StickersFragment.java
app/src/main/java/org/fossasia/phimpme/editor/view/StickerView.java

Fixed #1816 
Changes: Clip the sticker canvas to the size of the main bitmap during the preview.

Fix #1816 - Applying sticker out of image.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #1820 
Changes: Error message is displayed as a floating label in the edittexts when entering wrong password, the floating label(error message) dissappears when the user starts typing the password once again after the failed attempt.

Fix #1820-Error message displayed when entering wrong password.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #1822
Changes: Now there is only one way to open settings, that is, from the navigation drawer. Removed this option from the overflow menu when you are in AlbumsMode.

Fix #1822 Removed settings option from the overflow menu

---

app/src/main/res/layout/image_description.xml
app/src/main/res/values/strings.xml

Fixed #1850
Changes: The information is now properly assigned with their respective tags. Also added a "2dp" bottom margin to avoid the problems faced in the issue #1634. Since I added a "2dp" bottom margin so reduce the height of the view (from 10dp to 8dp) that provides space between tags in details view. Also assigned a common textSize to the information in details view.

Fix #1850 - information is now properly with their tags.

---

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistoryAdapter.java

Fixed #1531 
Changes: Added an onClickListener() and if that media is not available a Snackbar msg is shown.

Fix#1531:Upload History Image Opens

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #1863 
Changes: Added checks for `albumsMode` and `orientation`

Fix #1863 - Pinch now works for landscape mode as well as photos.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #1880
Changes: Removed the line which was causing the null pointer exception.

Fix #1880 App doesn't crash on opening favourites photos in SingleMediaActivity

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/res/layout/activity_leafpic.xml
app/src/main/res/values/strings.xml

Fixed #1659 
Changes: Appropriate message is displayed if the results are null on performing the search folder operation.

Fix #1659-Appropriate message is displayed if search results are null.

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/StickersFragment.java
app/src/main/res/values/dimens.xml

Fix #1938 - sticker size not accurate

---

app/src/main/res/layout/activity_share.xml

Fixed #1926
Changes: Added margin on top,bottom,right and left of the image to make the UI look better.

Fix #1926 - Toolbar doesn't overlap with the image

---

app/src/main/jni/filters.cpp
app/src/main/jni/filters.h
app/src/main/jni/main_processing.cpp
app/src/main/res/values/arrays.xml

Fixed #1921 
Changes: Added a cartoonify filter option
Original 
After filter:

Fix #1921 - Add a cartoon filter.

---

app/src/main/jni/filters.cpp
app/src/main/jni/filters.h
app/src/main/jni/main_processing.cpp
app/src/main/res/values/arrays.xml

Fixed #1877 
Changes: Added a pencil sketch filter in edit mode. Made required changes in cpp files.
After filter :

Fix #1877 - Add pencil sketch filter in edit mode.

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/SliderFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/StickersFragment.java
app/src/main/res/drawable/ic_close_black_24dp.xml
app/src/main/res/layout-land/fragment_edit_image_add_text.xml
app/src/main/res/layout-land/fragment_edit_image_crop.xml
app/src/main/res/layout-land/fragment_edit_image_rotate.xml
app/src/main/res/layout-land/fragment_edit_paint.xml
app/src/main/res/layout/fragment_edit_image_add_text.xml
app/src/main/res/layout/fragment_edit_image_crop.xml
app/src/main/res/layout/fragment_edit_image_rotate.xml
app/src/main/res/layout/fragment_edit_paint.xml
app/src/main/res/layout/fragment_editor_slider.xml
app/src/main/res/layout/fragment_editor_stickers.xml

Fixed #1901 
Changes: Material design icons used for both apply and cross, and both icons are set to same width and height.
Screenshot before the change:
Screenshot after the change:

Fix #1901-Edit Functionality material design close icon issue fixed.

---

app/build.gradle
app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
app/src/main/res/menu/main.xml
app/src/main/res/menu/menu_bottom_view_pager.xml

Fixed #2008 
Changes: The bottombar's menu item "action_favourites" was being referenced in the onPrepareOptionsMenu method which is responsible for preparing the overflow menu, as a result of which null pointer exception was caused. Removing the reference in the onPrepareOptionsMenu got the code working.

Fix #2008-App crash fixed.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2011
Changes: Add to favorites and edit options for images in the upload history are not displayed anymore. 

Fix #2011 - Upload History image view issue fixed.

---

app/src/main/java/org/fossasia/phimpme/data/local/ImageDescModel.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2037 
Changes: On moving a photo to another path, the path attribute of the realm description object for the particular photo is updated from the old path to new path. Therefore the saved description for the photo is displayed on selecting the add description option.

Fix #2037-Issue in the add description functionality resolved.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2055 
Changes: Compress option not available when viewing upload history images.

Fix #2055 - Removed compress option from UploadHistory.

---

app/proguard-rules.pro

Fixed #2092 
Changes: Configured proguard file to keep the twitter4j classes when building the apk.

Fix #2092-App crash fix for twitter option in AccountsActivity.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2071
Changes: On clicking the delete icon on the app bar in favorites section(non-edit mode), only photos from the fav collection are removed not the corresponding photo albums in the Local albums section.

Fix #2071-Fixed delete operation issue in Favourites section.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
app/src/main/res/values/strings.xml

Fixed #2113
Changes: "Rename Image" is displayed as the dialog title instead of "Rename album".
Screenshot for the change:

Fix #2113-Rename image feature dialog issue resolved.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #1858 
Changes: With this fix, when the user opts to edit any image in the favorites section and then aborts it and swipes to the next image and tries editing again the correct image is displayed.

Fix #1858-Favourite section edit issue resolved.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java
app/src/main/res/layout/dialog_security_folder.xml
app/src/main/res/layout/secure_folder_dialog_item_view.xml

Fixed #1777
Changes: Choose folders to secure dialog view items visible properly for darker themes.

Fix #1777-Choose folders to secure dialog issue resolved.

---

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistoryAdapter.java

Fixed #2141 
Changes: App crash fixed for navigating to Upload History with no item shared.

Fix #2141-Fixed app crash for Upload History section.

---

app/src/main/java/org/fossasia/phimpme/gallery/util/AlertDialogsHelper.java
app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinAdapter.java
app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistoryAdapter.java

Fixed #2131 
Changes: The checkbox is now tinted in the accent color irrespective of its state(checked or unchecked).

Fix #2131-Checkbox tint issue for delete operation resolved.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java
app/src/main/res/values/strings.xml

Fixed #2061 
Changes: Now on deleting images that have been shared and have a record in the Upload History, the upload history record persists. An option is provided to the user to delete the upload history record of the image by navigating to the Upload History section.

Fix #2061-Shared images delete issue resolved.

---

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java
app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistoryAdapter.java

Fixed #2144 
Changes: There is some error while using the DiffUtil class for populating the recyclerview adapter, therefore have switched to using the notifyDataSetChanged() till the DiffUtil issue is resolved. Will solve the DiffUtil issue via another separate PR.

Fix #2144-Fixes upload history crash.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #1829 
Changes: On changing the screen orientation while viewing photos in albums or allphotosmode, the position of the scrollbar remains same i.e the user is not taken to the starting of the album, the photos are displayed from the same position as before the orientation change.

Fix #1829-Position of scrollbar remains same on orientation change.

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/FrameFragment.java

Fixed #2160 
Changes: While navigating through the tabs at the bottom of the editing activity a separate Async task is called for loading the ArrayList attached to the tab. This ArrayList is null in the beginning and is initialized only when the doInBackground() method is called leading to crashes (ArrayList.size() causes null pointer Exception). So i implemented the OnpreExecute() method for Async Tasks and initialized the list in this method.

Fixed #2160 App does not crash while navigating quickly between editing tabs 

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/data/HandlingAlbums.java
app/src/main/java/org/fossasia/phimpme/utilities/SnackBarHandler.java

Fixed #2158
Changes: [(LFMainActivity.java).First get all the images of the selected albums and then add them to database and move all the images to .nonmedia Folder which is selected folder for storing images (trash bin), also add other stuff like restore when click on undo in Snackbar. (HandlingAlbums.java) returning the selected Album arrayList and (SnackBarHandler.java) showing and refreshing the list ]

Fix #2158 Delete albums operation issue

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/PaintFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/RotateFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/SliderFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/StickersFragment.java
app/src/main/java/org/fossasia/phimpme/editor/view/CustomPaintView.java

Fixed #2173 
Changes: [All files which i changed they call different image processing method on a null object of bitmap so i changed all the methods will invoke only if bitmap is not null and if it's null it will also remove that fragment if i didn't do that then it make more and more stack of fragment on activity.]
Gif of the change:

Fix #2173 (App crashed when changing the orientation)

---

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java

Fixed #2189 
Changes: [transaction add() in fragment added the fragment on above of another so i used replace() to make only one fragment at time at the preview container]

Fix #2189 (Fragment overlapping on orientation change in the edit image section)

---

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java

Fixed #2201 
Changes: [Traditionally savedInstanceState() used to restore the state of activity so implement it in EditImageActivity to restore selected fragments.]

Fix #2201 (Fragment should remain same after orientation changed)

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/PaintFragment.java
app/src/main/res/layout-land/fragment_edit_image_add_text.xml

Fixed #2205 
Changes: The list of colors in the paint option was  horizontal so i changed it to a vertical list and also the add text option had a horizontal linear layout so i changed it to vertical linear layout.

Fixed#2205 Improved the UI of the add text and the paint

---

app/src/main/res/layout-land/fragment_editor_frames.xml

Fixed #2206
Changes: The preview container resizes itself as per the size of the contents(landscape-mode) to enhance user experience. But the layout file for frames had some constraints leading to the issue #2206. These constraints were appropriate for portrait mode but not for landscape mode. So i created a layout-land file for frames fragment with appropriate constraints. 

Fixed#2206: Created layout-land resource file for frames

---

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java

Fixed #2239 
Changes: Presently the Snapchat function used intent.setpackage() function which was however unable to open the required activity in snapchat so i replaced it with setComponent().

Fixed#2239 Used setcomponent instead of setpackage for Snapchat

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/CropFragment.java

Fixed #2194 
Changes: [crash due to calling the null bitmap because of changing the orientation so i apply few conditions in order to stop the app crashes.]
GIF  of the change:

Fix #2194 app crashes in crop fragment depends on orientation

---

app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java

Fixed #2271 
Added the button tint list attribute to checkbox and called the accent color from theme.
**Screenshots of the change:**

Fixed#2271 Added the button tint list attribute to checkbox

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java
app/src/main/res/drawable/custom_background.xml

Fixed #2213 
Changes:Now a message is shown when password is set or changed.

Fix for issue #2213 : No message is shown while setting password

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java

Fixed #2289 
Changes: When a set password is removed, a message is shown to the user indicating that the password has been removed.
Gif of the change:

Fix for #2289 :A message is shown when password is removed

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java

Fixed #2281 
Changes: Removed library Loglr. The library Loglr declared for the purpose of Tumblr authentication was adding SMS permissions at build time.

fix #2281-SMS permission issue resolved

---

app/src/main/res/layout/dialog_password.xml

Fixed #2333 
Changes: 
forgot password is now aligned on the side of show password checkbox.

fix#2333 forgot password alignment issue

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2226 
Changes: [Added a new method for showing the toolbar when it goes from album to photos screen]

Fixed #2226 Actionbar hidden on second screen when scrolls down in first screen 

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java
app/src/main/res/values/strings.xml

Fixed #2338 
Changes: the edit field hint of password dialog was changed accordingly for initial setup and change password. 

password edit field hint changed to new password

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java
app/src/main/res/layout/dialog_password.xml
app/src/main/res/layout/dialog_set_password.xml

Fixed #2339 
Changes: Forgot password text color is now the same as show password and the color also changes according to the theme.

Fix for issue#2339 : Forgot password text color made same as show password.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java
app/src/main/res/values/strings.xml

Fixed #2214 
Changes: Whenever a password is being set or being changed, alerts are shown if fields are not filled appropriately.

Fix for issue#2214 : Alerts are shown when password parameters are incorrect.

---

app/src/main/res/layout/activity_drawer.xml

Fixed #2321 
Changes:  paddingTop was added to the layout enclosing the concerned ImageView.
<table>
<tr>
<th>Before Change</th>
<th>After Change</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/25201519/50416046-7a0d4880-0844-11e9-9f66-1ae5d0bd7083.jpeg" width="300"></td>
<td><img src="https://user-images.githubusercontent.com/25201519/50416045-7a0d4880-0844-11e9-9c00-e2140477b458.jpeg" width="300"></td>
</tr>
</table>

fix: Phimpme logo in navigation drawer overlaps status bar

---

app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java

Fixed #2366 
Changes: 
swipe to refresh disabled for empty trash bin ui.

refresh action disabled for empty trash bin ui

---

app/src/main/AndroidManifest.xml

This makes the Activity(EditImageActivity) to retain it's state even after rotation and hence prevents the app from crashing while inserting text to the image.
In the AddTextFragment.java file the mTextSticketView was getting null
due to restarting of the activity due to which the app crashed. This fix
allows the activiy to retain its state after rotation and hence the
mTextStickeerView is no longer null.
Fixed #2192

fixes the crashing of app due to orientation change.

---

app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java
app/src/main/res/layout/dialog_forgot_password.xml
app/src/main/res/values/strings.xml

Fixed #2349 
Changes: Forgot password dialog now shows an error instead of closing when wrong answer is entered.

Fix for issue#2349: An error is shown when forgot password answer is wrong.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java

Fixed #2369 
Changes:Secure local folder dialog cannot be closed if the user taps the screen anywhere outside the dialog. Hence the app also doesn't crash anymore. 

Fix for issue#2369: Prevented dialog from closing on outside touch.

---

app/src/main/res/drawable/ic_search_black_24dp.xml
app/src/main/res/values/styles.xml

Fixed #2399 
Changes: Unused drawable file ic_search_black_24dp.xml is deleted.

Fix #2399 - Remove redundant drawable ic_search_black_24dp

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SplashScreen.java
app/src/main/res/values/strings.xml

Fixed #2363, #2411 
Changes: When the dialog is shown to the user to give permissions, the user has the option to go to app settings and grant permissions from there.

Fix for issue#2363: Option added for user to give permissions from app settings.

---

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java

Fixed #2433 
Changes: Corrected position of SnackBar in accounts activity when internet connection is off. I also added a button to the SnackBar to directly let the user pen data usage settings and switch on mobile data.

Fix for issue#2433: Fixed position of SnackBar.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java

Fixed #2461 
Changes: Replaced the reset settings snackbar with a toast so that it is always visible.

Fix for issue#2461: Replaced reset settings snackbar with a toast.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2442 Made navigation drawer visible onResume where ever required.
Changes: LFMainActivity.java

Fix #2442 Made navigation drawer visible onResume where ever required.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java

Fixed #2477 
Changes: 
accent color change dialog button changed to yes and no

accent color change dialog button changed to yes and no

---

app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java

Fixed #2392 
Changes: After resetting the password, the user is directly shown the insert password screen instead of the forgot password dialog screen.

After resetting password forgot password dialog is dismissed.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/res/layout/activity_leafpic.xml
app/src/main/res/values/strings.xml

Fixed #2476 
Changes:
star image now changes color as per the primary color.
empty favourite string was split into two parts.
styling of the textview was done.

empty favourite photos ui improved

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java

Fixed #2209 
Changes: there is two initial value for middle and bottom fragment which is temporary and after initialization all the fragment changes done by default flow (using mode).

Fix #2209 layout changes issue

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2485 
Changes:
delete action made invisible unless some media is selected.

deleting from favourite now requires selecting an image first

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2535 
Changes: Colors for highlighting the text in dark and amoled themes have been changed so that they are properly visible.

Fix for issue#2535: Changed highlight colors in dark and amoled theme.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2563 
Changes: 
password removed from single media favourite icon.
snackbar is shown when image is removed using the icon.

password removed from single media favourite icon

---

app/src/main/java/org/fossasia/phimpme/gallery/adapters/AlbumsAdapter.java

Fixed #2540 for better privacy, first image of locked folders are not visible. 
Changes: Albums adapter is slightly modified.
**Screenshots**

Fix #2540 first locked image should not be visible

---

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java

Fixed #2508
Changes:
password dialog now dismisses after giving correct password.

password dialog dismissed after execution

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java
app/src/main/res/values/strings.xml

Fixed #2518 
Changes:
snackbar to restart the app after theme change was added.

snackbar to restart after theme change added

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixes #2595 
Changes: added click listener for keyboard enter

Fix #2595 in slideshow set timer dialog, keyboard enter can be used as ok button

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2470 
Changes: Snackbar does not overlap the bottom bar anymore.

fix: Fixed snackbar positions.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/res/menu/menu_albums.xml
app/src/main/res/values/strings.xml

Fixed #2210 
Changes: LFMainActivity.java, menu_albums.xml, strings.xml Added option to remove selected photos from favorites in options menu. This option is visible only when any one of the selected photos is in favorites.

Fix #2210 Added feature to remove multiple photos from favourites from album itself.

---

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java

Fixed #2480
Changes:
1/2
swipe to refresh disabled for empty upload history folder.

swipe to disabled for empty ui

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
app/src/main/res/values/strings.xml

Fixed #2599 
Changes: Once an image is set as the cover photo, it can be removed as the cover photo from the menu in SingleMediaActivity itself.

If an image it set as the cover image, it can be removed as the cover image if it is opened.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/res/values/strings.xml

Fixed #2583 
Changes: A proper message is shown when more than one image is deleted and moved to trash bin.

fix: Trashbin message for more than one images being deleted.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java

Fixed #2676
Changes:
access by password and apply theme were made toggleable, i.e, now they can turned on just by tapping on the view.

access by password and apply theme were made toggleable

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/CropFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/PaintFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/RotateFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/SliderFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/StickersFragment.java

Fixed #2454 
Changes: [changeMode method call before the fragment transaction executed so that's why there is no object initialization in fragment and i used to store value in mode variable which is using at initialization of fragment]

Fix #2454 App Crashing

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2639
Changes: Added button to snackbar to open favourites in single media activity

Added button to snackbar to open favourites in single media activity

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2597 #2626 
Changes: checked the number of images in album and handled visibility of sort menu

Fix #2597 sort images menu made invisible when there is only one image in album

---

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java

Fixed #2534 
Changes: [Changing the orientation does not destroy the fragment , it detached the fragment so when the activity recreated it attach the fragment so when we again call the method setInitialFragments has add method  which add another fragment cause two selected option.]

Fix #2534 After orientation change showing two selected option in edit mode

---

app/src/main/AndroidManifest.xml

Fixed #2527 
Changes: [after adding adjustNothing in manifest makes no size change effect on actionbar]

Fix #2527 actionbar size issue

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2200 
Changes: LFMainActivity.java. Disabled drawer when selecting albums and re-enabled it when no albums are selected.

Fix #2200 Disabled drawer when selecting albums.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2630 
Changes: Album cover and slideshow buttons show up only if there are two or more images in an album.

fix: Fixed visibility of menu buttons.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2649 
Changes: The bottom bar of the app does not pop up while deleting multiple photos from favorites.

fix: App bar does not pop up while deleting photos from favourites.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java

Fixed #2565 
Changes: User can now click on the folder name as well as the checkbox to select the folder to be secured.

Folder name can be clicked to check the check box in secure folders dialog.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2580 
Changes: The extra space in the share message has been removed.

fix: Extra space removed from share phimpme message

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2591 
Changes: The highlighted color of text while changing image is visible in every theme.

fix: Text highlight is visible in all themes.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/ExcludedAlbumsActivity.java
app/src/main/res/layout/activity_excluded.xml
app/src/main/res/menu/menu_excluded_items.xml
app/src/main/res/values/styles.xml

Fixed #2567 
Changes: Restore all excluded items directly instead of selecting one by one

Fix #2567 Include all options in excluded item list

---

app/src/main/AndroidManifest.xml

Fixed #2598
Changes: Now the bottom bar is not visible when the keyboard pops up in single media activity.

fix: Keyboard does not push app bottom bar up.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2603 
Changes: Location text color in image details is now the same as an accent color for the app instead of staying yellow all the time.

fix: Made location text color same as accent color.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2605 
Changes: changed text highlight color on the album rename dialog in dark amoled theme

Fix #2605 TextHighlight in rename dialog visible in dark amoled theme

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java

Fixed #2622 
Changes:
restart action was added to translucent status bar.

added restart action to snackbar

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2632 
Changes: 
cancel button added to request sd card permissions. now the user can exit the dialog without giving permissions.

added cancel button to request sd permissions dialog

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java

Fixed #2611 
Changes: A snackbar is shown if a password is set again after removal.

fix: Snackbar is shown if password is set again after removal.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2612 
Changes: Toast replaced with snackbar, key listener added on alert Dialog EditText

Fix #2612 in slide show, toast replaced by snackbar and keyboard doesn't close on invalid time interval

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2635 
Changes: 
fixed the position of snackbar after granting sd card permissions

fixed the position of snackbar after granting sd card permissions

---

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java

Fixed #2596 
Changes: highlight visible in caption dialog

Fix #2596 text highlight visible in caption dialog in dark amoled theme

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2620
Changes: Added scroll listener and fab button on albums screen

Fix #2620 go to top fab added to albums activity

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java
app/src/main/res/layout/color_piker_accent.xml

Fixed #2671 
Changes: 
unnecessary gap in dialog removed.

unnecessary gap in text and paint color palette dialog removed.

---

app/src/main/res/values/arrays.xml

Fixed #2664 
Changes: Made the tile of red color filter "Red Boost" like the other color filters. Also changes "B/W" to  "Black & White".

fix: Change the filter titles.

---

app/src/main/res/layout-land/fragment_editor_twoitem.xml

Fixed #2529 
Changes: Fixed position of the buttons in landscape mode.

fix: Position of buttons.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java

Fixed #2513 
Changes: A common convention has been made for all security related dialogs. The ok button is on the left and cancel on the right.

Fix for issue#2513: Made a convention common for all security dialogs. 

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/AddTextFragment.java

Fixed #2504 
Changes: [AddTextFragment uses the bitmap from the activity so when the orientation change activity is recreated but fragment not so it uses the null bitmap so i make the condition before using the bitmap]

Fix #2504 app crash in edit text

---

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java

Fixed #2525 
Changes: [calling the runtime permission in onResume can create a infinite loop if user deny the permission so i check that if user deny permission temporary or permanent and return if permanent deny the permission.]

Fix #2525 Back button get stuck when there is deny of permission

---

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/MyPreferenceFragment.java

Fixed #2521 
Changes: The user is given the choice of restarting the app immediately or later. If the user does not want to restart the app immediately, the changes are made when the app is closed and restarted by the user whenever the user closes the app and restarts it manually.
Screenshot of the change:

fix: An alert is shown to the user asking whether app should be restarted or not.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2638 
Changes: Some snackbars were being shown earlier but their position was wrong. their position has been corrected. Some snackbars were earlier created in the app but were not being displayed. They are now displayed. There was also no snackbar to indicate that gif creation had been done. A snackbar for gif creation has been added.

fix: Snackbars in LFMain activity and added snackbar for gif creation.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2610 
Changes: Now a photo cannot be renamed if the user renames with the same name.

fix: A photo cannot be renamed with the same name.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2721
Changes: [Add condition so it can disable the swipe to refresh layout in favorite section as well all photos ]

Fix #2721 disable swipe to refresh

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2553
Changes: [Add a condition where it checks if we are in hidden folder or not then it proceeds.]

Fix #2553 reappear of password dialog

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/StickersFragment.java

Fixed #2703 
Changes: [Added a condition if there is not sticker then do not perform the undo and redo functions]

Fix #2703 undo and redo enable issue

---

app/src/main/res/layout/image_description.xml

Fixed #2528 
Changes: The complete padding on the linear layout which was causing visibility issues has been removed. Instead, padding was added individually to the views which required it.

fix: Fixed the position of description.

---

app/build.gradle

Fixed #2735 
Changes: Android 5.0 has been set as the minimum required SDK.

chore: Made Android 5.0 as minimum SDK

---

app/src/main/java/org/fossasia/phimpme/opencamera/UI/PopupView.java

Fixed #2574 
Changes: [I put the condition that if it's already selected that means it will store in the shared preference then don't go for dialog .]

Fix #2574 HDR mode dialog issue

---

app/src/main/jni/Application.mk
app/src/main/res/values/styles.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

* Use a supported STL.
* Fix bad style reference (aapt2 catches this).
* Update gradle plugin to one compatible with NDK r16+.
This still isn't sufficient because the OpenCV prebuilts are gnustl
only, but it's a starting place for anyone that can tackle that.

Fixes for NDK r19.

---

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
app/src/main/java/org/fossasia/phimpme/share/flickr/FlickrActivity.java
app/src/main/java/org/fossasia/phimpme/share/twitter/LoginActivity.java
app/src/main/java/org/fossasia/phimpme/share/wordpress/WordpressLoginActivity.java
app/src/main/java/org/fossasia/phimpme/utilities/SnackBarHandler.java

Fixed #2467 
Changes: The snackbar handler class was missing a return statement. The return statement has been added and snackbars have been changed accordingly and are now visible everywhere.

fix: snackbars are now visible everytime SnackbarHandler is called.

---

.travis.yml
scripts/update-apk.sh

Changes: Initial attempt for the auto release process.

feat: Automatic release process

---

app/build.gradle
app/src/main/AndroidManifest.xml

Fixed #2748 
Changes: Moved app version code and name to the gradle file.

chore: Moved app version code and version name to gradle file.

---

.travis.yml

Changes: Made changes in the travis.yml file. Now instead of 3 parallel jobs, 2 jobs are run in series. Time taken is approximately the same.

chore: Changes in travis.yml

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java

Fixed #2416 
Changes: On opening camera setting for the first time/after resetting the app, a dialog was being shown, which had no use. This dialog has been removed and the function modified accordingly.

fix: Removed redundant camera dialog

---

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java

Fixed #2550 
Changes:
- If the user presses OK, the user is directed to permissions screen of the app.
- If the user presses Cancel, a dialog is shown that camera permission is necessary.
- If the user presses Deny and do not show again in the 2nd dialog, the user has to manually o to app settings to give permission.

fix: Provided option for user to give camera permission by opening permissions screen.

---

app/src/main/res/drawable/ic_location_on_black_48dp.xml
app/src/main/res/xml/preferences.xml

Fixed #2654 
Changes: Icons changed to match the entire app theme.

fix: Icons in camera settings made matching with the app theme

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java

Fixed #2723 
Changes: 
- If user presses `gallery` button while in albums mode(home screen), refresh action does not take place.
- If the user is viewing photos inside an album, and presses `gallery`, the user is redirected to home.

fix: No action if home button is pressed in gallery itself.

---

app/src/main/java/org/fossasia/phimpme/editor/CompressImageActivity.java
app/src/main/res/values/strings.xml

Fixed #2629 
Changes: A toast is shown when a user compresses an image. (A toast is shown as snackbar is not visible properly due to the presence of a background dialog)

fix: Toast shown when image is compressed.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java

Fixed #2675 
Changes: Title changes to remove album cover as soon as a photo is set as the album cover.

fix: Title changes to remove album cover as soon as a photo is set as the album cover.

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
app/src/main/res/values/strings.xml

Fixed #2590 
Changes: If an image is deleted or moved to trashbin from the SingleMediaActivity, a snackbar is shown. Removed the `showsnackbar` method as we need different messages when albums and images are deleted.

fix: Added snackbars when image is deleted from SingleMediaActivity.

---

.travis.yml
app/src/main/java/org/fossasia/phimpme/editor/fragment/StickersFragment.java
app/src/main/res/drawable/ic_red_dialog_alert.xml
app/src/main/res/values/strings.xml

Fixed #2656 
Changes: If user presses tick button in stickers section without using any sticker, an alert is shown. 
I have not used `button.setEnabled(false);` because it will make the user confused as to why the tick button is not working.

fix: Added alert if user clicks tick button in stickers section without adding any stickers.

---

app/src/main/java/org/fossasia/phimpme/editor/CompressImageActivity.java
app/src/main/java/org/fossasia/phimpme/editor/font/FontPickerDialog.java
app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java

Fixed #2687 
Changes: All cancel buttons in app have `cancel` in upper case now. 
The `cancel` in the dialog in camera setting can not be made upper case as it is not actually a dialog, but a popup and the cancel button seems to be a default part of the popup as I was unable to find that piece of code anywhere.

fix: All cancel buttons made upper case

---

app/src/main/java/org/fossasia/phimpme/editor/CompressImageActivity.java

Fixed #2701 
Changes: Compress dialogs do not disappear after orientation change.

fix: Dialog does not disappear on orientation change

---

app/build.gradle
build.gradle
gradle.properties
openCV/build.gradle
pdk/build.gradle
photoview/build.gradle

Fixed #2763 
Changes: Changes `compile` to `implementation`, `debugCompile` to `debugImplementation` and other related changes. Also, updated versions of dependencies used.

chore: Removed obsolete configurations and updated versions of dependencies.

---

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java
app/src/main/res/values/strings.xml

Fixed #2771 
Changes: If the user is not able to save images, the user is directed to the permission settings.

fix: If photo is not being saved, user is guided to the permission setting to give proper permission.

---

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java

Fixed #2787 
Changes: Prevented dialogs n edit image activity from being dismissed when orientation is changed.

fix: Prevented other dialogs in edit activity from being dismissed on orientation change.

---

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/AddTextFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/CropFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/PaintFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/RecyclerMenuFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/RotateFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/SliderFragment.java
app/src/main/java/org/fossasia/phimpme/editor/fragment/StickersFragment.java
app/src/main/java/org/fossasia/phimpme/editor/view/CustomPaintView.java
app/src/main/java/org/fossasia/phimpme/editor/view/RotateImageView.java
app/src/main/java/org/fossasia/phimpme/editor/view/StickerItem.java
app/src/main/java/org/fossasia/phimpme/editor/view/StickerView.java
app/src/main/java/org/fossasia/phimpme/editor/view/imagezoom/ImageViewTouchBase.java
app/src/main/res/layout-land/fragment_editor_recycler.xml

Fixed #2702 
Fixed #2789 
Changes: All edits in an image are stored when orientation change happens.
GIF:

fix: Edited changes are saved on orientation change.

---

.travis.yml
scripts/update-apk.sh

Fixed #2797 
Changes: Attempt to fix the auto release script.

chore: Fixed auto-release script

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java

Fixed #2455
Changes: Added a background progress dialog for copy/move and delete actions.

fix: Added a background dialog for delete, copy/move actions

---

build.gradle

Fixed #2846 
Changes: Updated build gradle version to 3.4.2 which is the latest.

chore: Update build gradle version being used

---

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/ExcludedAlbumsActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
app/src/main/java/org/fossasia/phimpme/gallery/activities/SplashScreen.java
app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java
app/src/main/java/org/fossasia/phimpme/opencamera/Camera/MyPreferenceFragment.java
app/src/main/java/org/fossasia/phimpme/opencamera/Camera/PhotoActivity.java
app/src/main/java/org/fossasia/phimpme/opencamera/Preview/Preview.java
app/src/main/java/org/fossasia/phimpme/opencamera/UI/FolderChooserDialog.java
app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
app/src/main/java/org/fossasia/phimpme/share/drupal/DrupalLogin.java
app/src/main/java/org/fossasia/phimpme/share/flickr/FlickrActivity.java
app/src/main/java/org/fossasia/phimpme/share/twitter/LoginActivity.java
app/src/main/java/org/fossasia/phimpme/share/wordpress/WordpressLoginActivity.java
app/src/main/java/org/fossasia/phimpme/utilities/SnackBarHandler.java
app/src/main/java/org/fossasia/phimpme/utilities/Utils.java

Fixed #2593 
Changes: Replace snackbars with snackbarshandler

fix: Replace snackbars with snackbarshandler

---

app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java
app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java

Fixed #2722
Changes: Swipe to refresh had been earlier disabled in some activities. But as per the discussion on issue #2722, it shouldn't have been.

fix: Swipe to refresh enabled for all activities

---

app/src/main/java/org/fossasia/phimpme/gallery/activities/SplashScreen.java

Fixed #2863 : Permission flow change in splash screen
Changes: No need to restart app when user gives the permission

fix: Permission flow in splash screen

---

app/build.gradle

Fixed #2867 
Changes:  updated buildtools, targetsdk, compilesdk version to 29

chore: updated buildtools, targetsdk, compilesdk version to 29

---

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java

Fixed #2806 
Changes: EditImageActivity has been changed to store instance of AddText Fragment when device is rotated and restore the instance of the same fragment when activity is created again after device rotation.

fix: Text in edit image screen disappears on rotation

---

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
build.gradle

Fixed #2879 bump: nextcloud sdk to v1.5.0
Changes: Upgraded dependency of nextcloud

chore(deps): nextcloud sdk to 1.5.0

---

app/build.gradle
app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
app/src/main/java/org/fossasia/phimpme/share/imgur/ImgurPicUploadReq.java
app/src/main/java/org/fossasia/phimpme/share/imgur/ImgurPicUploadResp.java
app/src/main/java/org/fossasia/phimpme/utilities/Constants.java
app/src/main/java/org/fossasia/phimpme/utilities/ImgurApi.java
app/src/main/java/org/fossasia/phimpme/utilities/RetrofitClient.java
build.gradle

Fixed #2895 
Changes: Removes volley and shifts to retrofit

feat: Removed volley and shifted api calls to retrofit

---

app/src/main/java/org/fossasia/phimpme/editor/fragment/CropFragment.java

Fixed #2318 
Changes: was getting empty text in on saved instance state, handled that

fix: crash on orientation change while crop

---

build.gradle

Fixed #2906
Changes: Updated build.gradle file , Bumped the Gradle version from 3.5.0 to 3.5.2

chore(deps): Bump gradle from 3.5.0 to 3.5.2

---

app/build.gradle
app/src/main/java/org/fossasia/phimpme/base/BaseActivity.java
app/src/main/java/org/fossasia/phimpme/opencamera/Preview/Preview.java
app/src/main/res/values/strings.xml

Fixed #2930 
Changes: Removed material showcase library

fix: removed materialshowcase libary due to crash on android 10

---

docs/sources/conf.py
docs/sources/index.rst
scripts/upload-gh-pages.sh

Fixed #2964 
Changes: 
- Include `readme.md` to the `index.rst`
- Modify `upload-gh-pages.sh` to,
- Copy image files
- Install m2r plugin which used to include readme file.
Preview link: https://kumuditha-udayanga.github.io/phimpme-android/

Build website with Travis using README.md

---

.travis.yml
docs/sources/conf.py
docs/sources/index.rst
scripts/upload-gh-pages.sh

Fixed #2967 
Changes:
- Add sphinx material theme to the documentation site.
- Add a new job to travis.yml to deploy documentation to gh-pages (to configure python 3)
- Modify `upload-gh-pages.sh` script.
Preview link: https://kumuditha-udayanga.github.io/phimpme-android

Add material UI theme to documentation site

---

.travis.yml
README.md
docs/sources/conf.py
docs/sources/index.rst

Fixed #2973 #2974 
- Added https://sphinx-git.readthedocs.io/en/latest/index.html git-sphinx for changeLog
- Added the hosting page link as per #2973 
PREVIEW: https://sid911.github.io/phimpme-android/
Don't worry the changelog heading is above the changelog.... its just like that in the preview because its coming from another branch which is old 😅

Added Changelog in website

---

app/src/main/res/values/styles.xml

Fixed #3031
Changes: Changed AMOLED DARK MENU THEME style  to dark in styles.xml

Menu item not visible properly in Trash Bin Dark AMOLED theme fixed

---

app/src/main/java/org/fossasia/phimpme/gallery/util/ThemeHelper.java
app/src/main/res/values/styles.xml

Fixed #3017 
Changes: 
Added a function in ThemeHelper Class.
Created a function which handle switch colour update on change in Basic theme(in setting section).

Setting Switch state not visible properly in Dark AMOLED basic theme
