fossasia/phimpme-android

.idea/misc.xml, .travis.yml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/vn/mbm/phimp/me/image/CropImage.java, app/src/main/java/vn/mbm/phimp/me/ultils/osmap/ItemizedOverlayWithBubble.java, app/src/main/res/layout/add_wordpress_account.xml, build.gradle
#6 #2 
- Updated the SDK version and compileSDKversion. Added addon-google_apis-google-19 as app is GoogleAPI version.
- Fixed the transformClassesWithDexForDebugwarning as it is ignoring the inner class attribute.
- Fixed com.android.dex.DexIndexOverflowException.
- Fixed transformResourcesWithMergeJavaResForDebug it is because of duplicates files due to libraries. Excluded files for now.
- Set Instantiatable Lint preference to warnings
Some random UI fixes. As I will restructure the code.
=> Fixed Travis ci integration

.idea/misc.xml, .travis.yml, app/build.gradle, build.gradle, build.sh
Added the jacoco plugin and required scripts for integration with travis.
#8
=> Codecov integration working

.travis.yml, sample-apk/test.txt, upload-apk.sh
Added **upload-apk.sh** which copies the generated apk file in sample apk directory.
Thanks @the-dagger for script
#3
=> Upload sample apk on every commit.

.idea/misc.xml, app/src/main/AndroidManifest.xml, app/src/main/java/vn/mbm/phimp/me/Camera2.java, app/src/main/java/vn/mbm/phimp/me/PhimpMe.java, app/src/main/java/vn/mbm/phimp/me/Settings.java, app/src/main/java/vn/mbm/phimp/me/Upload.java
- Changing front/ back camera now working in every phone.
- app not crashing after image click.
- Filters working.
#15
=> Camera bugs fixed

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/vn/mbm/phimp/me/MyApplication.java, app/src/main/java/vn/mbm/phimp/me/Upload.java, app/src/main/java/vn/mbm/phimp/me/UploadProgress.java, app/src/main/java/vn/mbm/phimp/me/Webkit.java, app/src/main/java/vn/mbm/phimp/me/feedservice/FacebookActivity.java, app/src/main/java/vn/mbm/phimp/me/utils/PrefManager.java, app/src/main/res/layout/facebook_layout.xml, app/src/main/res/values/strings.xml
The core feature of the app - Upload Images is now working for Facebook.
- Integrate facebook login in app using facebook sdk
- Retrieve details such as access token, User id, name, profile url and add it to the database.
- Fixed adding account multiple times by setting preference.
- Use SDK's share photo to post Images to facebook.
- Working for single/ multiple images.
Issues : #16, #12, #11
=> Upload single/ multiple images to Facebook.

.travis.yml, upload-apk.sh
@mariobehling With this PR I fixed #27, you can check it. the apk that is and will be generated with every commit is "app-debug.apk", you can find it in the folder "sample-apk" in the branch "apk", if you want to check it, here it is a [Link](https://github.com/Heredroky/phimpme-android/blob/apk/sample-apk/app-debug.apk). You can see that it is automatically generated by checking the commits of the "apk" branch.
After the explanation above, now I am going to tell you how make it work in fossasia's repository, you have to follow this steps:
1. Merge this PR
2. Generate a Personal Access Token on Github and check the following options:
3. Go to the [Travis phimpme-android page](https://travis-ci.org/fossasia/phimpme-android)
4. Go to settings
5. Go to Environment Variables and create one …
=> Automatically apk update

app/src/main/res/drawable/circle_shape.xml, app/src/main/res/drawable/circular_progress_bar.xml, app/src/main/res/layout/dialog_add_account_drupal.xml, app/src/main/res/layout/dialog_add_account_joomla.xml, app/src/main/res/layout/dialog_add_account_wordpress.xml, app/src/main/res/layout/gallery.xml, app/src/main/res/layout/gallery3d_movie_view.xml, app/src/main/res/layout/gallery_grid_photos_item.xml, app/src/main/res/layout/gallery_private_grid_photos_item.xml, app/src/main/res/layout/new_wordpress_account.xml, app/src/main/res/layout/personalgallery.xml, app/src/main/res/layout/splash.xml, app/src/main/res/layout/upload_map.xml
Improved design of the app.
Done as part of GCI task: https://codein.withgoogle.com/dashboard/task-instances/5305516907560960/
**Describing the changed layouts one by one**
1.
After:
[There was some button overflows which looked bad]
2.
Before:
After:
3.
Before: 
After: 
4.
Before: 
After: 
_This change has affected many layouts (i.e, I changed the same before layouts to after) The progressbar also spins acting as a spinner via the files added to the `drawable/` folder _
5. 
Before:
After:
6.
Before:
After:
I did not bother to change the core theme as I don't want to do this without a discussion. So I opened issue #30. After that we could modify the core design to complete material one. (Here I am implementing some partial tweaks to materialize only a small part of the app.)
=> Imporved design

.gitignore, .idea/gradle.xml, sample-apk/test.txt, upload-apk.sh
Issue #27 
Need to to little editing after merging. Rest is fine.
=> upload apk in apk branch

README.md
Added some features of the app with their current status in the Readme.
#33
=> added Features List in Readme

app/src/main/java/vn/mbm/phimp/me/Upload.java
Replaced OnTouchListener() with OnClickListener()
=> Fix: Add Account button firing multiple times

app/src/main/java/vn/mbm/phimp/me/GalleryMap.java, app/src/main/java/vn/mbm/phimp/me/OpenStreetMap.java, app/src/main/java/vn/mbm/phimp/me/PhimpMe.java, app/src/main/java/vn/mbm/phimp/me/PhimpMeGallery.java, app/src/main/java/vn/mbm/phimp/me/Upload.java, app/src/main/java/vn/mbm/phimp/me/newGallery.java
@pa1pal I've removed my previous PR and made a new one to the _development_ branch! Can you review? :)
=> refactor: Replaced deprecated managedQuery() with getContentResolver().query()

app/src/main/java/vn/mbm/phimp/me/PhotoSelect.java
The query handler used which is **managedQuery()** is deprecated! Replaced it with _**getContentResolver().query()**_
=> fix: App crashing on adding picture at Upload

.idea/gradle.xml, .idea/misc.xml, .idea/vcs.xml, app/src/main/java/vn/mbm/phimp/me/Settings.java
Fixes App crashing issue which occurred while trying to delete downloaded photos
=> Fixes app crash on deleting downloaded photos

.github/ISSUE_TEMPLATE, .github/PULL_REQUEST_TEMPLATE
Fixes #54 Added PR and Issue templates.
=> Fixes issue #54 Add PR and Issue templates

.idea/modules.xml, app/build.gradle, app/src/main/java/vn/mbm/phimp/me/newGallery.java
=> Fixed Crash on newGallery.java

.travis.yml
Fixes issue #65 Travis tried to deploy the app to apk on pull requests
Changes: Now apk will build on direct commits.
=> Fixes #65 Deploy the app to apk on pull request merge

app/src/main/java/vn/mbm/phimp/me/BluetoothShareMultipleFile.java, app/src/main/java/vn/mbm/phimp/me/image/CropImage.java, app/src/main/res/layout/dialog_add_account_drupal.xml, app/src/main/res/layout/main.xml, app/src/main/res/layout/phimpme_gallery_view.xml, app/src/main/res/layout/phimpmegallery.xml, app/src/main/res/values-de/gallery3d.xml, viewflow/src/main/AndroidManifest.xml
* Removed unused xml namespace declaration. 
* Added ,Toast.LENGTH_LONG and Toast.LENGTH_SHORT instead of integer values. 
* Added View.VISIBLE and View.INVISIBLE intead of integer values.
* Aligned import statements
=> Refactor: Removed unused code, refactored toast message length and view visilibilty

app/src/main/java/vn/mbm/phimp/me/Camera2.java
=> Fix: Crash on switching camera

app/src/main/java/vn/mbm/phimp/me/Camera2.java, app/src/main/java/vn/mbm/phimp/me/newGallery.java, app/src/main/res/layout/newgallery.xml
Implemented a lazyload mechanism to handle large galleries
Fixes issue #[72]
Changes:
- Earlier the whole gallery was loaded when the app is starting
- That has a bad impact on huge galleries
- A lazyload implementation is used to load 21 images per once
=> fix: Local Photos Not Responding [ #72 ]

app/build.gradle, app/src/main/java/vn/mbm/phimp/me/PhimpMe.java, app/src/main/res/anim/fragment_anim_fadein.xml, app/src/main/res/anim/fragment_anim_fadeout.xml
Changes: Added a fadeIn / fadeOut animation on Fragment Change.
=> Adding Fade Animation on fragment replace

.travis.yml
=> modified travis.yml to cache gradle files

app/build.gradle, app/src/androidTest/java/vn/mbm/phimp/me/CameraActivityTest.java, app/src/androidTest/java/vn/mbm/phimp/me/ElapsedTimeIdlingResource.java, app/src/androidTest/java/vn/mbm/phimp/me/MainActivityTest.java, app/src/androidTest/java/vn/mbm/phimp/me/SettingsActivityTest.java, app/src/androidTest/java/vn/mbm/phimp/me/UploadActivityTest.java
Fix: Implement UI tests with Espresso
Changes: Added Espresso tests.
=> Fix Implemented UI tests with Espresso

app/src/main/java/vn/mbm/phimp/me/newGallery.java
Fixes issue #112 App crash on phones with less photos fixed.
=> Fixes #112 App crash fixed

app/src/main/java/vn/mbm/phimp/me/newGallery.java, app/src/main/res/layout/phimpmegallery.xml, app/src/main/res/layout/photoitem_local.xml
Added Shared Element transition on gallery grid.
=> Adding Shared Element Transition on Gallery Grid

README.md
Fixes issue #133 
Changes: Added link of contribute.md.
=> Adding link contribute.md file in Readme file #133

app/src/main/java/vn/mbm/phimp/me/gallery/PhimpMeGallery.java, app/src/main/res/drawable/ic_info_white_24dp.xml, app/src/main/res/layout/info_popup.xml, app/src/main/res/layout/phimpmegallery.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Fixes issue #125 Add option to check Image details
Changes: Added an info button which on being clicked displays the basic image information.
On small screens:
=> Fixes #125 Add option to check Image details

app/src/main/java/vn/mbm/phimp/me/CacheStore.java, app/src/main/java/vn/mbm/phimp/me/ImageItem.java, app/src/main/java/vn/mbm/phimp/me/gallery/PhimpMeGallery.java, app/src/main/java/vn/mbm/phimp/me/newGallery.java, app/src/main/res/drawable/ic_delete_white_24dp.xml, app/src/main/res/drawable/ic_deselect_white_24dp.xml, app/src/main/res/layout/newgallery.xml, app/src/main/res/layout/phimpmegallery.xml, app/src/main/res/layout/photoitem_local.xml, app/src/main/res/menu/menu_gallery.xml, app/src/main/res/values/strings.xml
Fixes issue #107 
Changes: 
- Implemented single image deletion
- Implemented multiple image deletion
- Multiple image deletion
- Single image deletion
=> fix: [ #107 ] Delete images

README.md
Updated Readme with new Screenshots
=> Updated Readme with new Screenshots

README.md
@Abhi2424shek This was not particularly a issue so i am directly send PR.
Changes: Fixed Grammatical Errors in README
=> Fixes Errors in README.md

app/src/main/java/vn/mbm/phimp/me/GalleryImagesAdapter.java, app/src/main/java/vn/mbm/phimp/me/newGallery.java, app/src/main/java/vn/mbm/phimp/me/utils/Params.java, app/src/main/java/vn/mbm/phimp/me/utils/Utils.java, app/src/main/res/layout/gridviewitem.xml, app/src/main/res/layout/image_item_imagepicker.xml, app/src/main/res/layout/photoitem_local.xml, app/src/main/res/values/dimens.xml
Fixes issue #185 
Changes: Implemented white circle tick as image selector everywhere
- Gallery
- Image Picker
- Upload image list
=> fix: [ #185 ] One selector for all image selectors

README.md, app/src/main/java/vn/mbm/phimp/me/Upload.java, app/src/main/res/values/strings.xml
Fixes issue #203 
Changes: Added Alert Dialog for confirmation from end user
=> Fixes #203

app/src/main/java/vn/mbm/phimp/me/Camera2.java
Fixes issue #190 Flash not firing at first launch.
=> Fixes #190 Flash fires according to image resource

app/src/main/java/vn/mbm/phimp/me/PhimpMe.java
Fixes issue #183 
Changes: Now on pressing back button in any activity dialog box will appear.
=> fixes issue #183

app/src/main/java/vn/mbm/phimp/me/gallery3d/media/CropImage.java, app/src/main/res/values/style.xml
Fixes issue #89. "First steps for issues.
Changes: When GPS is OFF and geolocation button is pressed, Alert dialog box pops to enable GPS.
=> Added alert dialog box to activate GPS

app/src/main/java/vn/mbm/phimp/me/Camera2.java
Fixes issue : Implement Tap to focus
Changes: Added Tap to focus functionality.
=> Fixes 1 of #162 Implement Tap to focus

README.md
Fixes issue #188 
Changes: [Add here what changes were made in this issue and if possible provide links.]
@Abhi2424shek Please Review :+1:
=> Enchanment: Instruction to clone dev branch

app/src/main/res/layout/phimpmegallery.xml, upload_apk_forks.sh
Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: 
changed src to srcCompat in PhimpMeGallery AppCompatActivity.
=> Fixed #232 App crashing on click on image

app/src/main/AndroidManifest.xml, upload_apk_forks.sh
#234 
Changes: Removed all unused code.
=> Issue 234 Fixed Remove unused code

CONTRIBUTING.md
Fixes erros in contribution.md @Abhi2424shek Please Review
=> Fixes Errors with Contribution.md

.travis.yml, CONTRIBUTING.md, app/src/main/java/vn/mbm/phimp/me/Camera2.java, app/src/main/java/vn/mbm/phimp/me/utils/Utils.java, app/src/main/res/layout/camera.xml, app/src/main/res/values/dimens.xml
Fixes issue #163 (Improvement) 
Changes: Removed hard coded dimensions from camera layout and added them pro-grammatically.
=> Removed hard Coded Dimensions from camera layout

app/src/main/java/vn/mbm/phimp/me/PhimpMe.java, app/src/main/res/layout/main.xml, app/src/main/res/menu/navigation.xml, gradle.properties
Fixes issue #244 
Changes:
Added ViewPager. Adapter is added as inner class to the Phimpme class. 
As the Map Fragment is loading a bit slow, So for now, to avoid the feeling of slow starting of application I swapped the positions of MapsFragment and Upload Fragment.
=>  Fixes #244 : View Pager added for navigation

app/src/main/java/vn/mbm/phimp/me/Camera2.java
Fixes issue #227 App crash while using Tap to focus on front camera fixed.
=> Fixes #227 App crash on using tap to focus fixed

app/src/main/java/vn/mbm/phimp/me/PhimpMe.java, app/src/main/java/vn/mbm/phimp/me/newGallery.java
Fixes issue #219 
Changes: if image is selected and user press back button image will be deselected
=> fixed issue #219 if image is selected and user press back button image is not deselected

app/src/main/java/vn/mbm/phimp/me/newGallery.java, app/src/main/res/drawable/ic_select_all_white_24dp.xml, app/src/main/res/menu/menu_gallery.xml, app/src/main/res/values/strings.xml
=> Fixes #194 : Add option to select all images in the image selector

app/src/main/java/vn/mbm/phimp/me/gallery/PhimpMeGallery.java
Fixes issue #218 
Changes: if fab button is open and user click outside then fab button get closed.
=> fixes issue #218

app/src/main/java/vn/mbm/phimp/me/MapFragment.java
Solving issue https://github.com/fossasia/phimpme-android/issues/171
=> Adding facility to open image on click from map

app/src/main/java/vn/mbm/phimp/me/newGallery.java
Fixes issue #311 
Changes:
The switch case block missed a return statement so it leaked to the next case which is for selecting all the images. Added the missing return statement!
=> fix: [ #311 ] Delete image option fixed!

app/src/main/java/vn/mbm/phimp/me/image/CropImage.java, upload_apk_forks.sh
Fixes issue #294 
Changes: 
- There was a issue with the saved bitmap image being recycled before drawing! Made a fix to that!
- Adjusted curly brackets to inlines
=> fix:[ #294 ] Crash fix in edit images

app/src/main/java/vn/mbm/phimp/me/newGallery.java
#290
Changes: Now user can able to scroll images in local gallery.
=> Fixed #290 Image should be scrollable

app/src/main/java/vn/mbm/phimp/me/newGallery.java
Fixes issue #173
Changes: Instead of changing the whole code and re-implementation, I modified the code such that the task that is performed when more button is clicked, will also gets performed when scrolled.
=> Fixes issue #173 Maximum images shown to user in gallery

app/src/main/java/vn/mbm/phimp/me/ImagePickerActivity.java
=> Fixes 264: Image picker Activity leaking window

app/build.gradle, app/src/main/java/vn/mbm/phimp/me/MapFragment.java
=> Fixes #247 : Initialise camera of the map fragment

README.md
simple broken link fixation
Fixes issue #315
Changes: changed the link to parent repo instead of a forked repo.
=> fixes #315

app/src/main/java/vn/mbm/phimp/me/PhimpMe.java
=> fixes issue #320 app crashing on pressing back button in activity except gallery

app/src/main/java/vn/mbm/phimp/me/Settings.java
=> fixes issue #323 back button not working properly

app/src/main/java/vn/mbm/phimp/me/image/CropImage.java
Fixes issue #296
Changes: There were unnecessary flags and checks for saving the picture. Removed it. It fixed the issue.
=> Fixes #296 Image cropping doesn't save the cropped image

app/src/main/java/vn/mbm/phimp/me/newGallery.java, app/src/main/res/menu/menu_gallery.xml
#318 
Changes: Now user can upload multiple images from gallery fragment. 
- added upload option in the menu.
=> Fixed #318 upload multiple images from gallery

app/src/main/java/vn/mbm/phimp/me/Settings.java, app/src/main/res/layout-land/settings.xml, app/src/main/res/layout/settings.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Fixes issue #327 
Changes: 
- Replaced individual radio buttons with a radio group!
| Light Theme | Dark Theme |
| --- | --- |
| ![1](https://cloud.githubusercontent.com/assets/14261304/24890783/69909ba6-1e8f-11e7-9a09-7d6f53036cc2.png) | ![2](https://cloud.githubusercontent.com/assets/14261304/24890789/70b49e0a-1e8f-11e7-898d-66387e5f0385.png) |
=> Closes #327 : Introduced radio group

app/src/main/java/vn/mbm/phimp/me/newGallery.java
Fixes issue #332 
Changes:
- Removed existing entries from the upload image list! :)
> Not available
=> Closes #332 : Upload imagelist gets updated upon deletion

app/src/main/java/vn/mbm/phimp/me/gallery/PhimpMeGallery.java
Fixes issue #217 
Changes: Now if image deleted then it will also removed from upload section.
=> fixes issue #217 issue with uploading images

app/src/main/java/vn/mbm/phimp/me/gallery3d/media/CropImage.java
Fixes issue #344 
Changes: added hide keyboard method in onResume so that soft keyboard not open automatically.
=> fix issue #344

app/src/main/java/vn/mbm/phimp/me/Camera2.java
Fixes issue #345 
Changes:
Just added handling multi touch and enabling pinch zoom in and out in camera preview. 
=> Fixes Issue #345: Pinch to Zoom in and out in camera preview added

app/src/main/java/vn/mbm/phimp/me/Camera2.java, app/src/main/res/drawable/ic_hdr_off_white_24dp.xml, app/src/main/res/drawable/ic_hdr_on_white_24dp.xml, app/src/main/res/layout/camera.xml
Closes issue #162  Implement HDR mode
Changes: Implemented HDR functionality in camera.
=> Closes #162 Implement HDR mode

app/build.gradle, app/src/main/java/vn/mbm/phimp/me/MapFragment.java, app/src/main/res/raw/map_dark.json
Changes: Added a Dark Map Style for Dark theme
=> Dark map for dark theme

app/src/main/java/vn/mbm/phimp/me/Camera2.java
Fixes issue #360 
Changes: 
- changed the way of checking boundary values for zoom
- changed condition for the zoom to work only for two finger gesture
=> closes issue #360 Zoom in camera is little buggy

app/src/main/java/vn/mbm/phimp/me/Camera2.java
Fixes issue #366 
Changes: Changed the value of zoom variable to slow down the zoom level as per the length of pinch.
=> Fix issue #366

app/src/main/java/vn/mbm/phimp/me/Camera2.java, app/src/main/res/drawable/ic_volume_off_white_24dp.xml, app/src/main/res/drawable/ic_volume_up_white_24dp.xml, app/src/main/res/layout/camera.xml
Fixes issue #369 Option to mute shutter sound
Changes: Button added to mute shutter sound
=> Closes #369 Option to mute shutter sound

app/src/main/java/vn/mbm/phimp/me/Upload.java
Fixes issue #377 
Changes: Buttons now match up with the theme.
=> Fixes #377

app/src/main/java/vn/mbm/phimp/me/Camera2.java, app/src/main/res/drawable/ic_exposure_white_24dp.xml, app/src/main/res/layout/camera.xml
Fix : Implemented Exposure controls
Changes:  Added option to control exposure
=> Fixes 1 of #380 Implement Exposure controls

app/src/main/java/vn/mbm/phimp/me/Camera2.java
Fixes issue #387 
Changes: made some changes in focus area.
=> fixes issue #387

app/src/main/java/vn/mbm/phimp/me/PhimpMe.java, app/src/main/java/vn/mbm/phimp/me/Upload.java
Fixes issue #392 
Changes: if image is selected and user press back button image will be deselected
=> fixes issue #392 issue with selected images in upload section

app/src/main/java/vn/mbm/phimp/me/Camera2.java
Fixes issue #391 
changes : we were using the old parameters in seekbar so I changed it and using new parameters in seekbar.
=> fixes issue #391 app is crashing in camera activity

app/src/main/java/vn/mbm/phimp/me/Camera2.java, app/src/main/java/vn/mbm/phimp/me/PhimpMe.java, app/src/main/java/vn/mbm/phimp/me/Settings.java, app/src/main/res/layout-land/settings.xml, app/src/main/res/layout/settings.xml, app/src/main/res/values/strings.xml
Fixes issue #384: Option to Capture the photo using Volume Buttons
Changes: Added the option to capture images using Volume Buttons
=> Closes issue #384: Option to Capture the photo using Volume Buttons

app/src/main/java/vn/mbm/phimp/me/Camera2.java, app/src/main/java/vn/mbm/phimp/me/PhimpMe.java
Fixes issue #398 
Changes: [Add here what changes were made in this issue and if possible provide links.]
=> Fixes issue #398 app is crashing in camera activity

app/src/main/java/vn/mbm/phimp/me/Camera2.java, app/src/main/java/vn/mbm/phimp/me/PhimpMe.java, app/src/main/java/vn/mbm/phimp/me/Settings.java, app/src/main/res/layout/settings.xml, app/src/main/res/values/strings.xml
Fixes issue #249 : Added option to enable/disable fetching the location from the GPS or the mobile network.
Changes: Added option in settings to enable/disable location.
=> Closes #249 Add option to enable/disable location

app/src/main/java/vn/mbm/phimp/me/ImageItem.java, app/src/main/java/vn/mbm/phimp/me/newGallery.java, app/src/main/res/layout/newgallery.xml
Fixes issue #416, #199 and part of #419.
Changes: 
- Changed GridView to recyclerView
- Added lazy loading using Glide
=> Fixes issues #416 Scroll in gallery page is not smooth

app/src/main/AndroidManifest.xml, app/src/main/java/vn/mbm/phimp/me/opencamera/CameraActivity.java, app/src/main/java/vn/mbm/phimp/me/opencamera/MyApplicationInterface.java, app/src/main/java/vn/mbm/phimp/me/opencamera/UI/DrawPreview.java, app/src/main/java/vn/mbm/phimp/me/opencamera/UI/MainUI.java, app/src/main/res/layout/activity_camera.xml, app/src/main/res/layout/activity_main.xml
Fixes issue #452 
Changes: 
**Before**
**After**
=> Improved camera UI

app/src/main/java/vn/mbm/phimp/me/opencamera/CameraActivity.java, app/src/main/java/vn/mbm/phimp/me/opencamera/MyApplicationInterface.java
Fixes issue #455 Camera brightness issue.
Changes: Removed the code to force brightness to max while opening the camera activity.
=> Fixes #455 Camera brightness issue fixed

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/vn/mbm/phimp/me/leafpic/activities/AboutActivity.java, app/src/main/java/vn/mbm/phimp/me/leafpic/activities/LFMainActivity.java, app/src/main/res/layout/activity_about.xml, app/src/main/res/layout/activity_drawer.xml, app/src/main/res/layout/activity_splash.xml, app/src/main/res/layout/toolbar.xml, app/src/main/res/values/strings.xml
=> Improved the about us section

app/src/main/res/layout/activity_settings.xml
Fixes issue #466 
Now Icons are visible.
Changes: 
**Before**
**After**
=> icons visibility for setting

app/src/main/java/vn/mbm/phimp/me/leafpic/activities/LFMainActivity.java
Fixes issue #470 
Changes:
Now bottom naviagtion color will be app primary color always.
=> #470 solved bottomNavigationColor

.travis.yml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/vn/mbm/phimp/me/Utilities/Utils.java, app/src/main/java/vn/mbm/phimp/me/accounts/AccountsActivity.java, app/src/main/java/vn/mbm/phimp/me/base/BaseActivity.java, app/src/main/java/vn/mbm/phimp/me/base/ThemedActivity.java, app/src/main/java/vn/mbm/phimp/me/leafpic/activities/LFMainActivity.java, app/src/main/java/vn/mbm/phimp/me/opencamera/CameraActivity.java, app/src/main/res/layout/activity_accounts.xml, app/src/main/res/layout/activity_camera.xml, app/src/main/res/layout/activity_leafpic.xml, app/src/main/res/layout/content_accounts.xml, app/src/main/res/layout/element_bottom_navigation.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, build.gradle
Fixes issue #468 
Changes: Fragment like implementation in bottomnavigationview using Acitivities. Added a abstract BaseActivity and two abstract functions for setting layout and navigation item.
=> Bottom navigation View implementation using Activities.

app/src/main/java/vn/mbm/phimp/me/leafpic/activities/SingleMediaActivity.java, app/src/main/res/menu/menu_view_pager.xml
Fixes issue #503 Rotate option in SingleMediaActivity
Changes: Removed option to rotate images
=> Removed option to rotate image

app/src/main/java/vn/mbm/phimp/me/leafpic/activities/LFMainActivity.java, app/src/main/java/vn/mbm/phimp/me/leafpic/data/Album.java, app/src/main/java/vn/mbm/phimp/me/leafpic/data/providers/MediaStoreProvider.java, app/src/main/java/vn/mbm/phimp/me/leafpic/data/providers/StorageProvider.java, app/src/main/res/menu/menu_albums.xml
Fixes issue #515 
Changes:
Removed the video options and video listing from the app.
=> removed video option from menu

app/src/main/java/vn/mbm/phimp/me/opencamera/Camera/CameraActivity.java, app/src/main/java/vn/mbm/phimp/me/opencamera/Camera/MyApplicationInterface.java, app/src/main/java/vn/mbm/phimp/me/opencamera/Camera/PreferenceKeys.java, app/src/main/java/vn/mbm/phimp/me/opencamera/CameraController/CameraController1.java, app/src/main/java/vn/mbm/phimp/me/opencamera/Preview/ApplicationInterface.java, app/src/main/java/vn/mbm/phimp/me/opencamera/Preview/Preview.java, app/src/main/java/vn/mbm/phimp/me/opencamera/UI/PopupView.java, app/src/main/res/values/arrays.xml
Fixes issue #511 Option to mute shutter sound
Changes: Added controls to enable/disable shutter sound in PopupView of camera.
=> Shutter sound controls added

app/build.gradle, app/src/main/java/vn/mbm/phimp/me/leafpic/activities/LFMainActivity.java, app/src/main/res/layout/activity_drawer.xml, app/src/main/res/values/strings.xml
Fixes issue #544 App option to share phimpme.
Changes: Added option to share phimpme via deep link which opens the application if it is installed in the phone or downloads the build via Github link which can later be replaced by Playstore.
=> Added App invite via Firebase deep link

app/src/main/AndroidManifest.xml, app/src/main/java/vn/mbm/phimp/me/opencamera/Camera/PhotoActivity.java, app/src/main/res/layout-land/activity_photo.xml, app/src/main/res/layout/activity_photo.xml
Fixes issue #550 
Changes: 
Added custom toolbar.
=> Custom Toolbar in photoActivity

app/src/main/java/vn/mbm/phimp/me/opencamera/Camera/PhotoActivity.java, app/src/main/res/layout-land/activity_photo.xml, app/src/main/res/layout/activity_photo.xml, photoview/src/main/java/uk/co/senab/photoview/PhotoView.java
Fixes issue #558 Implement Zoom functionality in PhotoActivity
Changes: Made use of PhotoView module for zoom functionalities
=> Added pinch to zoom in PhotoActivity

app/src/main/java/vn/mbm/phimp/me/leafpic/activities/LFMainActivity.java, app/src/main/java/vn/mbm/phimp/me/leafpic/activities/SingleMediaActivity.java, app/src/main/java/vn/mbm/phimp/me/leafpic/data/Album.java, app/src/main/java/vn/mbm/phimp/me/leafpic/util/StringUtils.java, app/src/main/res/menu/menu_view_pager.xml
Fixes issue #552 
Changes:
Removed rename image option from the gallery.
=> Removed rename option for images

app/src/main/java/vn/mbm/phimp/me/leafpic/activities/LFMainActivity.java
First steps for Issue# 561
Adds more comments in LFMainActivity.java
Changes: Added comments at many places in LFMainActivity.java. This increases readability of the code and makes the working of the code easier to understand.
=> Issue #561: Add more comments in LFMainActivity.java

app/src/main/AndroidManifest.xml, app/src/main/java/vn/mbm/phimp/me/base/BaseActivity.java, app/src/main/java/vn/mbm/phimp/me/opencamera/Camera/CameraActivity.java
Fixes issue #575 
Changes:
Now check with phimpme with any app for the camera.
Open WhatsApp and choose profile pic and select camera->phipme. Click photo.
=> Broadcast reciever is working properly

app/jni/photo_processing.c
Fixes issue #615 
Changes: Changed package name in native code.
=> Fixed crash in editor

app/src/main/java/org/fossasia/phimpme/editor/editimage/EditImageActivity.java, app/src/main/java/org/fossasia/phimpme/editor/editimage/fragment/SliderFragment.java, app/src/main/res/layout/activity_image_edit.xml
Fixes issue #584 
Changes: - Added before after button
- created a copy of original bitmap and shown that when button is touched.
=> added before after toggle button

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java
Fix #620 
Changes: 
Fixed home button crash.
=> Fixed home button crash

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.kt, app/src/main/java/org/fossasia/phimpme/base/RecyclerItemClickListner.java, app/src/main/java/org/fossasia/phimpme/data/DatabaseHelper.java, app/src/main/res/layout/accounts_item_view.xml, app/src/main/res/values/strings.xml
Fixes issue #582 
Added sign out feature in account manager.
Changes: 
Work in progress. Need to merge this PR after #574 because I created this branch from #574 PR.
The codacy bot issues already fixed in #574 will fix when merged.
=> Added sign out feature in account manager

app/src/main/java/org/fossasia/phimpme/editor/editimage/EditImageActivity.java
First steps for issues #628 
Changes: Added comments to EditImageActivity.java . This helps in understanding the code.
=> Issue #628: Added comments in EditImageActivity.java

app/src/main/java/org/fossasia/phimpme/editor/editimage/EditImageActivity.java, app/src/main/res/drawable/ic_undo_black.xml, app/src/main/res/layout/activity_image_edit.xml
Fix issue #633 
Changes: Created a tracking bitmap array and used them when undoing.
=> Added stepwise undo feature in editor

app/jni/filter.c, app/jni/photo_processing.c, app/src/main/java/org/fossasia/phimpme/editor/editimage/filter/PhotoProcessing.java, app/src/main/java/org/fossasia/phimpme/editor/editimage/fragment/RecyclerMenuFragment.java, app/src/main/res/values/arrays.xml
=> Added Image Filters

app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java, app/src/main/res/menu/menu_view_pager.xml
Fixes issue #645
Changes: Removed sort option while viewing an image in SingleMediaActivity.
=> Removed sort option from popupView in SingleMedia Activity.

.github/PULL_REQUEST_TEMPLATE, app/src/main/java/org/fossasia/phimpme/editor/editimage/EditImageActivity.java, app/src/main/res/layout/activity_image_edit.xml
=> fix: outOfMemory Exception. Removed the last edited action added latest action in list

app/src/main/java/org/fossasia/phimpme/accounts/AccountPickerFragment.java, app/src/main/java/org/fossasia/phimpme/editor/editimage/EditImageActivity.java, app/src/main/res/values/strings.xml
Fix #649 
Changes: Uses Login manager from facebook SDK to integrate fb login. Added database part in onSuccess of that.
=> feat: added facebook login in account manager

app/src/main/java/org/fossasia/phimpme/editor/editimage/EditImageActivity.java, app/src/main/res/drawable/ic_redo_black.xml, app/src/main/res/layout/activity_image_edit.xml, build.gradle
Fix #644
Changes:
Added different undo arraylist recycle mehod. Inserted new indexIndicator. Implemented redo feature.
=> added redo feature

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/Utils.java, app/src/main/res/values/strings.xml
Fix #635 and #664  
Changes: Display snackBar to display the message if Instagram is not installed. Display Snackbar if internet connection is not available.
- Check if Instagram is installed or not.
- Check if internet connection is available or not.
=> Checking if Instagram is installed or not and handling No internet connection error

app/src/main/res/layout/activity_security_layout.xml
=> Now Icons are visible in security settings

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java
Fix #663 
Changes: Implemented options to do the following from the all photos list:
1. Share.
2. Delete
3. Affix
4. Select All
Removed the copy to, move, rename albums options from the all photos list.
=> Added long click options to all photos list

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java
Fix #676 
Changes:
Fixed the album selected issue after renaming.
=> Fixed rename album selection issue

app/src/main/res/values/strings.xml
Fix #684 
Changes: Changed App name on Twitter while sharing image from sharing Activity
=> Fixed the name of the app in Twitter

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.kt, app/src/main/java/org/fossasia/phimpme/accounts/AccountAdapter.kt, app/src/main/res/layout/accounts_item_view.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
=> changed the layout account manager using swithes for sign in

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/leafpic/data/base/MediaComparators.java, app/src/main/java/org/fossasia/phimpme/leafpic/data/base/SortingMode.java, app/src/main/res/menu/menu_albums.xml
Fix #643 
Changes: Added conditions to sort the pictures when viewed from the all photos mode.
=> Sorting option fixed in all photos mode

app/src/main/res/values/strings.xml
Fix #695 
Changes: Changed firebase dynamic share link
=> Changed the firebase share dynamic link

app/src/main/java/org/fossasia/phimpme/leafpic/util/ThemeHelper.java
=> changed the app default primary color

README.md
Fix #708 
Changes: Added instructions to setup opencv static libraries in readme
=> added instructions to setup opencv in readme

app/src/main/java/org/fossasia/phimpme/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/data/local/AccountDatabase.kt, app/src/main/res/layout/activity_share.xml, app/src/main/res/layout/dialog_caption.xml, app/src/main/res/values/strings.xml
Fix #706 
Changes: 
Added new dialog box in sharing activity.
=> Added new dialog box for caption in sharing activity

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
Fix #694 
Changes: Delete the account entry on switch off action. 
Sign in and sign out works on simple switch action. 
Check with twitter entry.
Screenshot:
=> Signout on switch off action

app/build.gradle, app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/accounts/AccountAdapter.kt, app/src/main/res/layout/accounts_item_view.xml, app/src/main/res/layout/activity_accounts.xml, app/src/main/res/values/colors.xml
Fix #717 
Changes: 
Removed the card view and Instagram from account manager.
Note: There is some problem in colors in accounts activity ignore that in this PR.
=> Improved the UI of account activity

app/src/main/java/org/fossasia/phimpme/SharingActivity.java, app/src/main/res/values/strings.xml
=> Added an async task and dialog box for Twitter upload

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java
Fix #718 , #729
Changes:
1.  Now marking is shown on selecting any media from the all photos list.
2. Hide album button shows only when  album is selected.
=> Fixed selected media issue in all photos mode

app/src/main/java/org/fossasia/phimpme/SharingActivity.java, app/src/main/res/layout/activity_share.xml
Fix #737
Changes: Used `ImageViewTouch` in `SharingAcitivity` to get zoom feature in sharingActivity.
=> Used ImageViewTouch in shareActivity to enable zoom feature

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java, app/src/main/res/values/strings.xml
Fix #722 
Changes: 
- Open camera using Google Now command. 
- Choose between front and rear camera
- Click picture on "cheese"
Steps to test the command:
-> Open Google Now or give command "OK Google".
-> Give the command "Take a selfie" or "Take a photo".
-> Choose the camera front or back by giving the command ->"Front" or "Selfie" for the front camera. "Rear" or "Back" or "Normal" for the rear camera. 
-> Give command "Cheese" or "yes" to take the photo.
=> Added Google Interactive API to interact with the Camera

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/StorageUtils.java
Fix #742 
Changes:
Changed the camera directory where captured images get saved.
=> Changed the camera directory where captured images get saved

app/src/main/java/org/fossasia/phimpme/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/sharetwitter/HelperMethods.java, app/src/main/java/org/fossasia/phimpme/utilities/Utils.java, app/src/main/res/layout/dialog_caption.xml, app/src/main/res/values/strings.xml
Fix #720 
Changes: 
Now we can upload any size of an image on Twitter.
=> Twitter large image support added

app/src/main/java/org/fossasia/phimpme/editor/editimage/filter/PhotoProcessing.java, app/src/main/jni/Android.mk, app/src/main/jni/main_processing.cpp, app/src/main/jni/photo_processing.c
Fix #745 
Changes: 
Added method for conversion of bitmap to mat and send mat to native.
Added receiving jni function for filter and tuning.
Added a edge detector function for checking the functionality.
=> added base functions for openCV

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/base/ThemedActivity.java, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java
Fix #739 
Changes: 
- Called proper set color funtions in activities.
- changed activity themes in manifest
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/15368561/27996434-89bd7f32-64ff-11e7-91db-4369ddc41ad2.png"></td>
<td><img src="https://user-images.githubusercontent.com/15368561/27996435-89c8ea8e-64ff-11e7-88af-d4e20f312999.png"></td>
<td><img src="https://user-images.githubusercontent.com/15368561/27996436-89c9c65c-64ff-11e7-9e27-15c4a255b2f3.png"></td>
</tr>
</table>
=> Made status bar, navbar and bottomnavigationview theme uniform

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/ImageSaver.java, app/src/main/java/org/fossasia/phimpme/utilities/BasicCallBack.java, app/src/main/java/org/fossasia/phimpme/utilities/Constants.java
Fix #762
Changes:
Added callback to send data of any type with status.
=> Added callback to send data of any type with status

app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java
Fix #750 
Changes: Fixed same description after changing the photo
=> Fixed same description issue after changing the photo

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java, app/src/main/res/values/strings.xml
Fix #758 
Changes: Added progress dialog and moved the numeric sort action in Async task
=> Fixed UI freeze on applying numeric sort action

app/build.gradle, app/src/main/java/org/fossasia/phimpme/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/data/local/AccountDatabase.kt, app/src/main/java/org/fossasia/phimpme/utilities/Constants.java, app/src/main/java/org/fossasia/phimpme/utilities/Utils.java, app/src/main/res/values/strings.xml
Fix #735 
Changes: 
Now you can upload an image to Imgur anonymously.
To check 
open -> share -> Imgur --> after successfully upload a link will be copied just paste in browser to verify.
=> Added imgur image upload feature

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
Fix #786 
Changes: Changed the value that is getting saved in realm database
=> Fixed name of pinterest logged in user

app/build.gradle, app/src/main/java/org/fossasia/phimpme/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/leafpic/util/AlertDialogsHelper.java, app/src/main/java/org/fossasia/phimpme/utilities/Utils.java, app/src/main/res/values/strings.xml
Fix #773 
Changes: 
Added Imgur upload dialog to share and copy a link.
=> Added Imgur upload dialog to share and copy a link.

app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/leafpic/data/Media.java, app/src/main/res/values/strings.xml
Fix #803 
Changes:Image description is now visible on the details dialog box.
=> Added image description in the details dialog box

app/src/main/java/org/fossasia/phimpme/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/sharewordpress/WordpressLoginActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/SnackBarHandler.java, build.gradle
Fix #788 
Changes: added a common Snackbar handler class for easy operations on Snackbar
=> added SnackbarHandler class and refactor the usage of SnackBar in code

app/src/main/java/org/fossasia/phimpme/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/sharedimgur/ImgurAuthActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/Constants.java, app/src/main/res/values/strings.xml
Fix #798 
Changes: 
Now you can upload an image from your Imgur account.
Follow the following steps:
1. Go to Accounts section for your Imgur account and log in with your credentials.
2. Open any image and click on share.
3. Choose Imgur and once an image is uploaded. 
4. Visit Imgur website and open Images to verify.
=> Integrated User auth and uploading from account on Imgur

app/src/main/java/org/fossasia/phimpme/SharingActivity.java, app/src/main/res/values/strings.xml
Fix #804 
Changes:
Added option to choose Imgur sharing Mode. 
=> Added option to choose Imgur sharing Mode

README.md, app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/Constants.java, app/src/main/res/layout/activity_share.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
Fix #791 
Changes: Added Dropbox image upload functionality from the Sharing Activity. 
**To upload image**
1. Login from the account manager.
2. Open share activity.
3. Click on Dropbox option
=> Added Dropbox image upload functionality

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/nextcloud/NextCloudAuth.java, app/src/main/res/drawable/back_round.xml, app/src/main/res/layout/activity_next_cloud_auth.xml, app/src/main/res/layout/view_color_more_panel.xml, app/src/main/res/values/dimens.xml
Fix #818 
Changes:
In editactivity paintview more color is not visible, changed the text color and enhanced NextCloud activity.
=> Enhanced NextCloud activity and paintview

app/src/main/res/layout/activity_drawer.xml
Fix #780 
Changes: 
Change Drawer Header background
=> Fix #780 - Change Drawer Header

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/res/layout/activity_share.xml, app/src/main/res/values/strings.xml
Fix #831 
Changes: Now the user can upload an image to Box storage from the ShareActivity.
** To upload image **
1. Replace the CLIENT_ID and CLIENT_SECRET in the Utilities/constant.java file.
2. Login to Box from account manager.
3. Select an image and go to share activity and select the Box option from the list.
=> Added upload image functionality to Box storage

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/data/local/AccountDatabase.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/share/flickr/FlickrActivity.java, app/src/main/java/org/fossasia/phimpme/share/flickr/FlickrHelper.java, app/src/main/java/org/fossasia/phimpme/share/flickr/tasks/UploadPhotoTask.java, app/src/main/java/org/fossasia/phimpme/utilities/Constants.java
Fix #821 
Changes: 
- Added realm database in flickr for storing tokens and other details of account.
- Updated details in accounts page
- Added caption support
=> Added realm in flickr and updated details in accounts page

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/res/layout/activity_next_cloud_auth.xml, app/src/main/res/layout/activity_share.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
Fix #834 
Changes: Added the OwnCloud item in sharing activity table item. 
Used the library to upload image (not working right now, might be due to some server error where I hosted account). I will follow this in subswquent PRs
Screenshot:
=> added feature to upload image to OwnCloud Account

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/NotificationHandler.java, app/src/main/res/drawable/ic_cloud_upload_black_24dp.xml, app/src/main/res/values/strings.xml
Fix #859 
Changes: Added notification handler class to show and dismiss notification progress while uploading an image on:
1. Box
2. Dropbox
3. Twitter
=> Added Notification handler class to show upload progress on twitter, box and dropbox

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/data/local/AccountDatabase.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/share/twitter/HelperMethods.java, app/src/main/java/org/fossasia/phimpme/share/twitter/LoginActivity.java, app/src/main/res/values/strings.xml
Fix #807 
Changes:
Fixed twitter first-time uploading issue.
Removed shared prefs to store key and secret. Using realm like other accounts.
=> Cleaned Twitter upload code and fixed first time error

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/res/values/strings.xml
Fix #862 
Changes: 
Now you can upload an image on Tumblr.
To check 
1. Add Tumblr keys in Constants.java class.
2. Sign in Tumblr from accounts.
3. Now share an image to Tumblr from share activity.
=> Added feature to upload image on Tumblr

app/src/main/java/org/fossasia/phimpme/leafpic/SelectAlbumBottomSheet.java, app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/leafpic/util/AlertDialogsHelper.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/res/values/strings.xml
Fix #812 
Changes: 
Changed the dialog box style to the Material design. 
Added URL to get the Board ID
Steps to reproduce:-> SharingActivity->Pinterest
=> Added description and URL in the Pinterest dialog box

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java, app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/leafpic/activities/SecurityActivity.java, app/src/main/java/org/fossasia/phimpme/leafpic/activities/SettingsActivity.java, app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/leafpic/activities/SplashScreen.java, app/src/main/java/org/fossasia/phimpme/leafpic/util/StringUtils.java, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/MyPreferenceFragment.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/share/twitter/LoginActivity.java, app/src/main/res/layout/activity_image_edit.xml, app/src/main/res/values/strings.xml
Fix #874 
Changes:
Changed Toasts to SnackBars in almost all places except in 
Camera (It has customToast and looks better than SnackBar in camera page)
In Some redundant static contexts in edit and photoactivity pages(Should be removed)
=> Replaced Toasts with SnackBars

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
Fix #882 
Changes: Changed the last authenticated check with Realm results
1. Login to box.
2. Close the application.
3. Open ShareActivity and share image to box now works fine.
=> Fixed login prompt for box storage from Share activity

app/src/main/java/org/fossasia/phimpme/share/ShareAdapter.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/Utils.java
Fix #845 
Changes:
Shows only the accounts that are connected from account activity
Shows imgur always and instagram, whatsapp if installed
=> shows only connected accounts in share activity

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/share/nextcloud/NextCloudAuth.java, app/src/main/java/org/fossasia/phimpme/share/owncloud/OwnCloudActivity.java, app/src/main/res/drawable/back_round.xml, app/src/main/res/layout/activity_next_cloud_auth.xml, app/src/main/res/values/dimens.xml
Fix #895 
Changes: Added check to add server address protocol in OwnCloud and NextCloud login page. Image wasn't uploading due to this. Tested and uploading image working.
=> added check for server address protocol in NextCloud and OwnCloud

app/src/main/java/org/fossasia/phimpme/utilities/Constants.java, app/src/main/java/org/fossasia/phimpme/utilities/Utils.java
Fix #911 
Changes:
Added common social package at constant class and replaced hard coded strings.
=> Added common social package at constant class

app/src/androidTest/java/org/fossasia/phimpme/leafpic/activities/CameraActivityTest.java, app/src/androidTest/java/org/fossasia/phimpme/leafpic/activities/ElapsedTimeIdlingResource.java
Fix #900 
Changes: 
1. Added espresso tests for Camera activity.
2. Added Idling resources for running tests successfully on all devices
Will implement Travis to run the tests on a different PR.
=> Added espresso tests for camera activity and added Idling resource

.travis.yml
Fix #930 
Changes: Changed AVD version to 22
=> Fix travis build fail issue

app/src/main/java/org/fossasia/phimpme/editor/FileUtils.java, app/src/main/java/org/fossasia/phimpme/editor/adapter/ColorListAdapter.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/BaseEditFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/CropFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/StickersFragment.java, app/src/main/java/org/fossasia/phimpme/editor/model/RatioItem.java, app/src/main/java/org/fossasia/phimpme/editor/model/StickerBean.java, app/src/main/java/org/fossasia/phimpme/editor/task/StickerTask.java, app/src/main/java/org/fossasia/phimpme/editor/ui/ColorPicker.java, app/src/main/java/org/fossasia/phimpme/editor/utils/BitmapUtils.java, app/src/main/java/org/fossasia/phimpme/editor/utils/DensityUtil.java, app/src/main/java/org/fossasia/phimpme/editor/utils/FileUtil.java, app/src/main/java/org/fossasia/phimpme/editor/utils/ListUtil.java, app/src/main/java/org/fossasia/phimpme/editor/utils/Matrix3.java, app/src/main/java/org/fossasia/phimpme/editor/utils/RectUtil.java, app/src/main/java/org/fossasia/phimpme/editor/view/CropImageView.java, app/src/main/java/org/fossasia/phimpme/editor/view/CustomPaintView.java, app/src/main/java/org/fossasia/phimpme/editor/view/CustomViewPager.java, app/src/main/java/org/fossasia/phimpme/editor/view/PaintModeView.java, app/src/main/java/org/fossasia/phimpme/editor/view/RotateImageView.java, app/src/main/java/org/fossasia/phimpme/editor/view/StickerItem.java, app/src/main/java/org/fossasia/phimpme/editor/view/StickerView.java, app/src/main/java/org/fossasia/phimpme/editor/view/TextStickerView.java
Fix #936 
Changes: cleaned the code base by deleting all unnecessary comments and adding Proper comments where ever necessary. In this way after the release of the application, it will be easy for a developer to understand the code properly
=> Cleaned the code base and changed all necessary comments

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/accounts/AccountAdapter.java, app/src/main/java/org/fossasia/phimpme/share/nextcloud/NextCloudAuth.java, app/src/main/res/layout/accounts_item_view.xml, app/src/main/res/values/styles.xml, gradle.properties
Fix #904 
Changes: Added a new style and applied it on `SwitchCompat`
Screenshot
=> fix: switch compat color using Styles

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java, app/src/main/res/drawable/ic_mic_black.xml, app/src/main/res/layout/dialog_description.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Fix #917 
Changes: Added voice input in description dialog box in SingleMediaActivity
=> Added Voice Recognition in Description dialog box. 

README.md
Fix #948 
Changes: 
- Added specific description of features. 
- Realigned the sections.
=> Updated Reamdme with description of features and re aligned

app/src/main/java/org/fossasia/phimpme/MyApplication.java, app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/share/twitter/HelperMethods.java, app/src/main/java/org/fossasia/phimpme/share/twitter/LoginActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/Constants.java, app/src/main/res/values/strings.xml
Fix #836 
Changes:
Moved all keys variable at one place. It will easy to add developer keys at one place.
=> Shifted all developers keys to one place

app/src/main/java/org/fossasia/phimpme/editor/fragment/RecyclerMenuFragment.java, app/src/main/jni/enhance.cpp, app/src/main/jni/filters.cpp, app/src/main/jni/filters.h, app/src/main/jni/main_processing.cpp, app/src/main/res/values/arrays.xml
Fix #909 
Changes: 
Added sajuno filter, manglow filter, palecia filter and anax filter 
Optimized other filters
=> Added 4 image filters and optimized other filters

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/data/local/AccountDatabase.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/Utils.java, app/src/main/res/drawable/ic_messenger_black.xml, app/src/main/res/values/colors.xml
Fix #929 
Changes:
Added option in shareactivity to share an image on messenger using SDK.
=> Added messenger option in shareactivity

app/src/main/java/org/fossasia/phimpme/leafpic/util/AlertDialogsHelper.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/res/values/strings.xml
Fix #969 
Changes: Added confirmation dialog before uploading images
=> Added confirmation dialog before uploading images

app/src/androidTest/java/org/fossasia/phimpme/leafpic/activities/SettingsActivityTest.java
Fix #954 
Changes: Added espresso UI tests for the settings activity
=> Added espresso UI tests for the settings activity

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/res/values/strings.xml
Fix #952 and Fix #951 
Changes:
=> Resolved Image upload on Google Plus and added appropriate snackbar while uploading

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java, app/src/main/java/org/fossasia/phimpme/opencamera/UI/MainUI.java, app/src/main/res/drawable/ic_zoom_in_white_24dp.xml, app/src/main/res/drawable/ic_zoom_out_white_24dp.xml, app/src/main/res/layout/activity_camera.xml, app/src/main/res/values/dimens.xml
Fix #970 
Changes: Removed the `zoom control` and added the Image Buttons.
It is showing large changes because I re formatted one file
=> modified the zoom controls using vector assets

app/src/main/res/values/colors.xml
Fix #984 
Changes: changed other share resources name
=> Fix: Crash on opening the share image activity with dark theme

app/src/main/java/org/fossasia/phimpme/base/BaseActivity.java, app/src/main/res/values/colors.xml
=> Fix #912 - Set color of tab icon bottom navigation view

app/build.gradle
Fix #940 
Changes: Testing more camera features:
Added resource file only to be in English, this would save space as automatically eliminates all resource files which in any other language than English
=> Allow resource string to be in english

app/src/main/AndroidManifest.xml
Fix #1001 
Changes: Fixed Pinterest authentication
=> Fix: Pinterest authentication

app/src/main/java/org/fossasia/phimpme/leafpic/util/Affix.java
Fix #994 
Changes: fixed the affixed folder and one folder in app named phimpme-edit
=> a common editing folder for all operations

app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java
=> Fixed update description issue

app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java, app/src/main/res/drawable/ic_photo_24dp.xml, app/src/main/res/menu/menu_albums.xml
Fix #1009 
Changes: 
Added icon in the menu instead of using getDrawble() method.
=> Fixed getdrawable crash in tablet

app/src/main/java/org/fossasia/phimpme/editor/FileUtils.java, app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/PhotoActivity.java
Fix #993 
Changes: 
found the extension from the path of the image and created the output file with that extension
=> Changed edited image format to that of input image

app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java
Fix #1019 
Changes: 
1. Now cursor points at the end of the line.
2. Giving voice input again concatenates with the previous input.
=> Enhancements while adding caption using voice input

.gitignore, app/src/androidTest/java/org/fossasia/phimpme/leafpic/activities/HomeScreenTest.java, app/src/androidTest/java/org/fossasia/phimpme/leafpic/activities/PhotoActivityTest.java, app/src/androidTest/java/org/fossasia/phimpme/leafpic/activities/SettingsActivityTest.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, download_open_cv.sh
Fix #1014 
Changes: Applied a workaround to fix the problem, the issue is with the android and it will be fixed in next android version.
=> fixed fileUriExposed exception while sharing image to whatsapp

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/Utils.java, app/src/main/res/layout/activity_share.xml, app/src/main/res/values/strings.xml
Fix #1013 
Changes:
Implemented voice integration on caption in sharing activity
Added promptSpeechInput in Util class. Now we can use easily voice input option anywhere.
=> Implemented voice integration on caption in sharing activity

app/src/main/java/org/fossasia/phimpme/MyApplication.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
Fix #978 
Changes: Added function to load image faster in the sharingActivity.
=> Added function to load image faster in Sharing Activity

app/fabric.properties, app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/Utils.java, app/src/main/res/values/strings.xml
Fix #1027
Changes:
Used global method for google voice and handled crash 
Fixed PDK crash in share activity.
=> Used global method for google voice and handled crash & Fixed PDK crash in shareactivity

app/src/main/java/org/fossasia/phimpme/data/local/UploadHistory.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
Fix #1030 
Changes: added another database model for upload history which which store the account name, image path, date and time.
=> added database mode for upload history and inserted values in it

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/MyApplicationInterface.java, app/src/main/java/org/fossasia/phimpme/opencamera/Preview/Preview.java, app/src/main/java/org/fossasia/phimpme/opencamera/UI/DrawPreview.java
Fix #1024 
Changes: Added functions to increase the screen brightness when clicking photos with screen flash on
=> Screen brightness now turns to max while taking pictures with screen flash on

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
Fix #1044 
Changes: Fixed Zoom in Images in sharing Activity. 
Loading Images Faster.
=> Fixed zoom in images in sharing Activity and loading Images faster

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/data/local/UploadHistoryRealmModel.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java, app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistoryAdapter.java, app/src/main/res/layout/activity_drawer.xml, app/src/main/res/layout/upload_history_activity.xml, app/src/main/res/layout/upload_history_item_view.xml, app/src/main/res/values/strings.xml
Fix #1030 
Changes: Added recycler view, Added adapter to load history data from database.
Steps to check:
Upload image to any service, Check history from navigation drawer item.
**Don't squash commits in this PR.**
=> added Upload History View

app/src/main/java/org/fossasia/phimpme/editor/FileUtils.java
Fix #1046 
Changes: 
fixed the strings in array and changed the returning string.
=> Fixed error in file extension

app/build.gradle, app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java, app/src/main/res/layout/activity_settings.xml
Fix #1055 
Changes: Removed option to zoom in/out using subscale image view
=> Removed the subscaling image view option from settings

app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/AddTextFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/CropFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/MainMenuFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/PaintFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/RecyclerMenuFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/RotateFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/SliderFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/StickersFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/TwoItemFragment.java, app/src/main/res/layout/fragment_editor_main.xml
Fix #1031 
Changes:
changed the background color of the active mode in main menu of editor.
=> Added selected option indicator in editor main menu

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/share/flickr/tasks/UploadPhotoTask.java, app/src/main/java/org/fossasia/phimpme/utilities/NotificationHandler.java, app/src/main/res/values/strings.xml
Fix #1057 
Changes: 
1. Added App Icon while uploading in Notification. 
2. Show proper message while uploading. 
3. Show notification for GooglePlus.
=> Enhances Notification handler with Proper tag and app icon

app/build.gradle, build.gradle
Fix #1067 
Changes: 
Removed Picasso library from the Gradle build.
=> Removed picasso library

app/src/main/java/org/fossasia/phimpme/opencamera/Preview/Preview.java, app/src/main/res/values/strings.xml
Fix #1002 
Changes: Added material Design showcaseview in CameraActivity when the toggle button is pressed to make the app look uniform.  
Removed ordinary showcase you from Gradle.
=> Added material Design Showcase view in camera Activity

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistoryAdapter.java, app/src/main/res/layout/upload_history_item_view.xml
Fix #1048 
Changes: added constraint layout in item view and followed the material design guidelines
=> Used constraint layout, ehnhanced the Item View of Upload History

app/src/main/java/org/fossasia/phimpme/gallery/adapters/ImageAdapter.java, photoview/src/main/java/uk/co/senab/photoview/PhotoView.java
Fix #1062 
Changes: 
Added zoomable support to gallery images using Photoview.
=> Added zoomable support to gallery images

app/src/main/java/org/fossasia/phimpme/MyApplication.java
Fix #1081 
Changes: Removed Crashlytics from the development branch
=> Removed the crashlytics from development branch

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java
Fix #1083 
Changes: 
1. Now the keyboard opens as soon as the insert password dialog opens
2. Did the code formatting for Settings activity and LFMainActivity
=> fix : Keyboard issue on opening the insert password dialog box

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fix #1091 
Changes: Added conditions to fix the null toast issue
=> fix: null toast issue on opening description dialog

app/src/main/java/org/fossasia/phimpme/gallery/data/Media.java
Fix #[1085
Changes: Add the degree character -> (char) 0x00B0
=> Fix #1085 - Add degree symbol for orientation

app/.directory, app/src/main/java/org/fossasia/phimpme/gallery/data/providers/StorageProvider.java
Fix #1102 
Changes: Add some conditional code
Before Fix:
https://goo.gl/c5Q65u
After Fix:
https://goo.gl/J7do2V
=> Fix: #1102 App Crashes while loading images

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/res/values/strings.xml
Fix #1148 
Changes: Now user has to press back twice to exit the app.
=> Fix #1148 - Add press back twice to exit

app/src/main/java/org/fossasia/phimpme/editor/fragment/SliderFragment.java
Fix #1162 
Changes: Now the save button is visible after applying Filter and Enhance.
=> Save button appears after applying filters

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fix #1173 Full Screen Toggle Working
Changes: Implemented RecyclerItemClickListner.OnItemClick Listener in SingleMedia Activity.
OnItemClick
@mohitmanuja Kindly review !
=> Fix #1173 Full Screen Toggle Working

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/anim/media_zoom_in.xml, app/src/main/res/anim/media_zoom_out.xml
Fix #1195 
Changes: added zoom in animation when the user clicks on a photo and zoom out when the user exits it.
=> fixes #1195 zoom in and zoom out animations added

app/src/main/res/layout/activity_settings.xml
Fix #1209 Now the text is visible properly.
Changes: Now the text is Visible
@anantprsd5 Kindly Review!
=> Fix #1209 - Text Visible in Settings Activity

app/src/main/java/org/fossasia/phimpme/opencamera/Camera/PhotoActivity.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/Constants.java
Fix #1194 
Changes: Now the preview does not close upon returning from the Share section.
=> Fix #1194 - Correct the flow in preview section.

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fix #1225 
Changes: Add background colour to the drawer item
=> Fix #1225 - Highlight current item in the drawer.

app/src/main/java/org/fossasia/phimpme/base/BaseActivity.java
Fix #1199 
Changes: Now when the user denies the permission to access external storage the Showcase Sequence doesn't begin.
=> Fixed App Intro Bug

app/src/main/java/org/fossasia/phimpme/data/local/UploadHistoryRealmModel.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
Fix #1226 
Changes: Add another variable 'status' to store the result of the sharing action.
=> Fix #1226 - Store result of share activity in database.

app/src/main/java/org/fossasia/phimpme/gallery/activities/ExcludedAlbumsActivity.java, app/src/main/res/layout/card_excluded_album.xml
Fix #1246 
Changes:Change to CardView.
=> Fix #1246 - Improve UI of excluded items.

app/src/main/java/org/fossasia/phimpme/gallery/data/Media.java
Fix #1259 
Changes:Only one date is displayed now
=> Fix #1259 only one date is displayed now

app/src/main/res/layout/accounts_item_view.xml
Fix #1256 
Changes: Added CardView for items to enhance the UI.
=> Fix #1256-Implemented cardview to enhance the AccountsActivity UI

app/src/main/java/org/fossasia/phimpme/gallery/adapters/AlbumsAdapter.java, app/src/main/res/layout/card_album.xml
Fix #1314 
Changes:Improved the UI of albums activity
Screenshots of the gallery for all the themes
=> Fix #1314 Improved the UI of albums activity

.travis.yml
Fix: #1341 
Fixes Travis Build fail issue
=> Fixes Travis

app/src/main/res/layout/activity_leafpic.xml
Fix #1232 
Changes: Scrollbar is now visible.
=> Scrollbar is visible in media recycler view

app/src/main/java/org/fossasia/phimpme/gallery/adapters/AlbumsAdapter.java
Fix #1288 
Changes: Change text color when media is selected.
=> Fix #1288 - Change text color of count for selected media.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/menu/menu_view_pager.xml, app/src/main/res/values/strings.xml
Fix #1261 
Changes:Now the user can print photos
=> Fix #1261 added an option to print photos

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fix #1270 
Changes: current drawer item is tinted in primary colour
=> Fix #1270 current drawer item is tinted in primary colour

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java, app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistoryAdapter.java, app/src/main/res/layout/upload_history_item_view.xml, app/src/main/res/values/strings.xml
Fix #1168
The UI of upload history was revamped.
@mohitmanuja @anantprsd5 Kindly review!
The colour of the title bar changes when the primary colour of the app changes.
Kindly suggest any more changes.
=> Fix#1168 Update UI of Upload History

app/src/main/java/org/fossasia/phimpme/gallery/SelectAlbumBottomSheet.java
Fix #1251 
Changes: soft keyboard now pops up automatically in create new folder dialog
=> Fix #1251 soft keyboard now pops up automatically 

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/data/Album.java, app/src/main/java/org/fossasia/phimpme/gallery/util/AlertDialogsHelper.java, app/src/main/res/layout/dialog_album_detail.xml, app/src/main/res/menu/menu_albums.xml, app/src/main/res/values/strings.xml
Fix #1241 
Changes: Added details dialog for album
=> Fix #1241 add details dialog for album

app/build.gradle, app/src/main/java/org/fossasia/phimpme/editor/fragment/RotateFragment.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/AboutActivity.java, app/src/main/res/layout/fragment_edit_image_rotate.xml
Fix #1301 
Changes: Replaced seekbar with HorizontalWheelView
=> Fixes #1301 HorizontalWheelView added

app/src/main/java/org/fossasia/phimpme/MyApplication.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/AddTextFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/BaseEditFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/CropFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/MainMenuFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/PaintFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/RecyclerMenuFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/RotateFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/SliderFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/StickersFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/TwoItemFragment.java
Fix #1381 
Changes: Made the Refwatcher in Application Class and added to watch in all the fragments present.
@aditya98ak @mayank8318 @mohitmanuja @anantprsd5 @sridharjajoo Please review!
=> Fix #1381 Refwatcher added

README.md
Fix #1418 
Changes: The **Get it on google play store** icon points to the correct page on selecting it.
=> Fix#1418 README.md points to the correct page

app/src/main/res/layout/activity_settings.xml
Fix #1318 
Changes: Add clickable property
=> Fix #1318 - Ripple for Force use of accelerometer.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fix #1379 
Changes: Now, if permission is not granted, it is asked, and thus delete is working fine now.
=> Fix #1379 Ask for sd Card permission for deletion

app/src/main/res/layout/accounts_item_view.xml, app/src/main/res/layout/activity_about.xml, app/src/main/res/values/strings.xml
#1407
Its better to use string resource rather than hardcore strings
=> Replaced Hardcore Strings with String Resource

README.md
=> Update README.md by removing typos

app/src/main/res/layout/select_folder_bottom_sheet_item.xml, app/src/main/res/values/dimens.xml
Fix #1430 
Changes: size of all icons reduced to original size
=> Fix #1430 size of all icons reduced to original size

app/src/main/java/org/fossasia/phimpme/editor/fragment/AddTextFragment.java
Fix #1427 
Changes: ImageView color is set on color change.
=> Fix#1427 - Color Issue Fixed

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fix #1441 
Changes: system is hidden in slideshow
=> Fix #1441 system UI is hidden in slideshow

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/layout/activity_pager.xml
Fix #1403 
Changes: App doesn't crash on rotation now
=> Fix #1403 app does not crash on rotation

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/data/AlbumSettings.java, app/src/main/res/menu/menu_view_pager.xml, app/src/main/res/values/strings.xml
Fix #1456 
Changes: Added option to change the cover photo of any album.
=> Fix #1456-Added option to change the cover photo of any album.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/MyPreferenceFragment.java, app/src/main/res/layout/activity_settings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Fix #1437 
Changes: added an option to restore default settings and removed it from the camera settings
=> Fix #1437 added option to restore default settings

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java, app/src/main/res/layout/dialog_password.xml
Fix #1465 
Changes: Wrong password error message is shown
=> Fixes #1465 Error message shown

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
Fix #1463 - Option added to delete caption in Sharing Activity
Changes: Added Delete option
=> Fix#1463- Delete button added to caption

app/src/main/java/org/fossasia/phimpme/data/local/FavouriteImagesModel.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/menu/menu_view_pager.xml, app/src/main/res/values/strings.xml
First step for issue #1289   
Changes: Upon clicking on the Add to favourites option in the menu, the photo uri is stored in the realm database.
=> Fix #1289 Added option to add photos to favourites table in the realm database.

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/res/drawable/ic_keyboard_arrow_up_black_24dp.xml, app/src/main/res/layout/activity_leafpic.xml
Fix #1475 
Changes: Add a FAB to scroll to top if there are a lot of photos.
=> Fix #1475 - Add a FAB to scroll to top.

app/src/main/java/org/fossasia/phimpme/gallery/adapters/AlbumsAdapter.java, app/src/main/res/drawable/pin.xml, app/src/main/res/layout/card_album.xml
Fix #1478 
Changes: Show a pin image near the album's name when the album is pinned to top.
=> Fix #1478 - Show an icon for pinned album.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fix #1462 Fixed slideshow major bug which I encountered with.
Changes: Added conditions and checks to recover from it.
Toast is displayed for slideshow not possible less than 2 sec.
@aditya98ak @mayank8318 @anantprsd5 @mohitmanuja Kindly review!
=> Fix #1462 - Slideshow bug fixed

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fix #1473
Changes: Snackbar is now visible on pressing backpressed in a few other devices as well in which it wasn't visible.
=> Fix:1473 Snackbar now visible in other devices

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fix #1460 
Changes: system UI does not get hidden when menu items or actionMenuView items are selected
=> Fix #1460 system does not get hidden when menu items are selected

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/layout/activity_pager.xml
Fix #1470 
Changes: Implement a `ViewSwitcher` instead of switching between two views manually.
=> Fix #1470 - Single Tap UI works on returning from details.

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Implements Butterknife in LFActivityMain.java and binds all views inside
it.
Changes:
Implements Butterknife in LFActivityMain.java It was not implemented
earlier.
Fixes #1500
=> LFActivityMain.java: Implements Butterknife

app/src/main/java/org/fossasia/phimpme/data/local/DatabaseHelper.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/values/strings.xml
Fix #1189 Delete Button Added in Description Dialog box for an Image
Changes: Added a Delete Button for alert dialog box of description.Shows Snackbar for any changes, error.
Included In the issue
@anantprsd5 Kindly Review!
=> Fix#1189- Delete Button Added In Description Alert

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fix #1538 
Changes: Slideshow working for all photos section.
=> Fix #1538-Slideshow working for all photos section.

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/AboutActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/data/Album.java, app/src/main/java/org/fossasia/phimpme/gallery/util/AlertDialogsHelper.java, app/src/main/java/org/fossasia/phimpme/gallery/util/CustomTabService.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/share/wordpress/WordpressLoginActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/SnackBarHandler.java, app/src/main/res/values/strings.xml
Fix #1516 
Changes: Removes hard-coded strings and adds string resources to strings.xml
Note: I have'nt edited log tags.
=> Removes hardcoded strings

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fix #1458 
Changes: Slideshow stops after displaying the last photo in the album.
=> Fix #1458-Slideshow stops after displaying the last media in the album.

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/res/menu/menu_albums.xml, app/src/main/res/values/strings.xml
Fix #1471 
Changes: A search option has been added to the menu of LFMainActivity . With the help of this the user will be able to filter the recycler view for the result he wants.
=> Implemeted search bar

app/src/main/res/xml/preferences.xml
Fix #1554
Changes: just added SwitchPreference named "preference_use_camera2" as key in preferences.xml
=> Fix #1554 Camera settings does not work

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java, app/src/main/res/layout/dialog_password.xml, app/src/main/res/layout/dialog_set_password.xml, app/src/main/res/values/strings.xml
Fix #1547 
Changes: Hints properly displayed, passwords can be entered in words as well, option to show/hide password enabled, toast is displayed when the maximum password length is reached.
=> Fix #1547-Changes in the security password dialogs.

.travis.yml, app/build.gradle, scripts/main_script.sh
Fixes #1633 
Configured Codecov to the Project
=> Fixes #1633 : Configured Codecov to the Project

app/src/main/java/org/fossasia/phimpme/MyApplication.java, app/src/main/java/org/fossasia/phimpme/gallery/animations/DepthPageTransformer.java, app/src/main/java/org/fossasia/phimpme/gallery/data/Media.java, app/src/main/java/org/fossasia/phimpme/gallery/util/CustomTabService.java, app/src/main/java/org/fossasia/phimpme/gallery/util/Measure.java, app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java, app/src/main/java/org/fossasia/phimpme/gallery/util/StaticMapProvider.java, app/src/main/java/org/fossasia/phimpme/gallery/util/StringUtils.java, app/src/main/java/org/fossasia/phimpme/gallery/util/ThemeHelper.java, app/src/main/java/org/fossasia/phimpme/share/twitter/AppConstant.java, app/src/main/java/org/fossasia/phimpme/share/twitter/HelperMethods.java, app/src/main/java/org/fossasia/phimpme/share/twitter/LoginActivity.java, app/src/main/res/values/strings.xml
- **Applied changes on ~12 files.**
- **Improved and optimized `strings.xml`**
- **Fixed some improper/broken strings.**
=> Fixes #1637 Enhances #1543 : Optimized strings.xml, refactored java files

app/src/main/res/menu/menu_bottom_view_pager.xml
Fix #1579 
Changes: Correct toast message is being displayed now
=> Fix #1579 correct toast message is being displayed

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java
Fix #1591 
Changes: 3 columns are visible in landscape mode
=> Fix #1591 improve upload history UI in landscape mode

app/src/main/java/org/fossasia/phimpme/gallery/activities/AboutActivity.java
=> Fix:1674 :Version number correctly shown

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fixed #1672 
Changes: Zip option is not visible for selected albums count greater than one, search option is not visible in the edit mode.
=> Fix #1672-Issues in the albums edit mode resolved.

app/src/main/java/org/fossasia/phimpme/gallery/SelectAlbumBottomSheet.java
Fix #1594 
Changes: Give theme based background color to the cards.
=> Fix #1594 - Give theme based background color to the cards.

app/src/main/java/org/fossasia/phimpme/gallery/util/AlertDialogsHelper.java, app/src/main/res/drawable/ic_folder_black_24dp.xml, app/src/main/res/drawable/ic_folder_white_24dp.xml, app/src/main/res/layout/dialog_album_detail.xml
Fix #1595 
Changes: Set up albums details according to the theme.
=> Fix #1595 - Improve UI of Albums details.

app/src/main/java/org/fossasia/phimpme/base/BaseActivity.java
Solution to issue #1506 
Changed the showcaseview so that it closed on touch outside.
Fix: Now the showcaseview closes on touch outside
Changes:Changed the showcaseview
=> Changed ShowcaseView

README.md
Corrected typos and Grammatical errors as mentioned in issue #1743
Fixed #1743 
"avaliable" changed to =>"available"
"performace" changed to =>"performance"
"recieve" changed to =>receive"
"succesfully" changed to =>"successfully"
Did some minor grammatical changes which enhance the readability of the file.
=> fixes #1743 Corrected typos and Grammatical errors

app/src/main/res/values/strings.xml
Fix #1713 
Changes: change the time interval message in edittext in slideshow dialog
=> Fix #1713 Modify description in slideshow dialog

app/src/main/AndroidManifest.xml
Fixed #1752
Changes:Changed the manifest 
Screenshot:
=> Fixed #1752-App now shows on sharing list

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java
Fixed #1767 
Changes: Print photo option was also visible in the LFMainActivity which was causing the crash. Removed print option from LFMainActivity.
=> Fix #1767-App crash on launch fixed.

app/src/main/jni/filters.cpp, app/src/main/jni/filters.h, app/src/main/jni/main_processing.cpp, app/src/main/res/values/arrays.xml
Fixed #1768 
Changes: 
Added a feature that converts the image into its negative form, that is it inverts the colours.
Before : 
After :
=> Added the Negative Images filter

CONTRIBUTING.md
Remove 'the' in point numbered '2' under pull request section that leads to a grammatical error.
Fixed #1755 
=> Fix #1755 Grammatical error in Contributing.md

app/src/main/jni/filters.cpp, app/src/main/jni/filters.h, app/src/main/jni/main_processing.cpp, app/src/main/res/values/arrays.xml
Fixed #1789 
Changes:
Added the Green Boosting filter in the Editor of the app which enhances the green component of the pixel.
Before : 
After :
=> Added the GreenBoost Effect

app/build.gradle
Fixed #1704 
Changes: The formatting of build.gradle file improved and added headings for similar group of libraries.
=> Fix#1704: Improved formatting of build.gradle file

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/res/drawable/ic_star_black_24dp.xml, app/src/main/res/layout/activity_leafpic.xml, app/src/main/res/values/strings.xml
Fixed #1747 
Changes: Add instructions for using the favourites feature.
=> Fix #1747 - Improve blank page for favourites.

app/src/main/res/menu/menu_albums.xml
Fixed #1731  Search button in actionbar
Changes:Now the search button is displayed in the actionbar with an icon
=> #1731 Fixed-Search button in actionbar

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/adapters/MediaAdapter.java, app/src/main/res/drawable/ic_star_black_24dp.xml, app/src/main/res/layout/card_photo.xml
Fixed #1746 
Changes: Add a star icon for favourite images.
=> Fix #1746 - Add a highlight(icon) on the favourite image.

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/res/values/strings.xml
Fixed #1688 
Changes: Format copy warning dialog box according to the app pattern.
=> Fix #1688 - Format copy dialog according to the app pattern.

app/src/main/java/org/fossasia/phimpme/editor/font/FontManager.java, app/src/main/java/org/fossasia/phimpme/editor/font/FontPickerDialog.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/AddTextFragment.java, app/src/main/java/org/fossasia/phimpme/editor/view/TextStickerView.java, app/src/main/res/drawable/ic_text_format_black_24dp.xml, app/src/main/res/layout/dialog_font_picker.xml, app/src/main/res/layout/fragment_edit_image_add_text.xml, app/src/main/res/values/strings.xml
Fixed #1802 
Changes: Added files to show the select font dialog box and a method in textSticker to set the typeface.
=> Fix #1802 - Give font choice to the user for TextStickers.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fixed #1856 
Changes: Make album cover option is not visible anymore on viewing the photo from the all photos section.
=> Fix #1856-All photos mode issue resolved.

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/base/BaseActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java, app/src/main/res/anim/left_to_right.xml, app/src/main/res/anim/right_to_left.xml
Fixes: #1825
Changes: Smoothened animation while switching activities.
=> Smoothened transition between base activities.

.github/PULL_REQUEST_TEMPLATE
Changes: Wrong spellings in line 3: ther.
Wrong Indentation in line 3: And starting just after a full stop.
Wrong grammar in line 5: for used instead of-of.
=> Wrong Spellings in PULL_REQUEST_TEMPLATE

app/src/main/res/layout/activity_drawer.xml
Fixed #1943 
Changes: Removed infutile ripple effect from the logo in-navigation drawer.
=> Removed infutile ripple effect.

app/src/main/jni/filters.cpp, app/src/main/jni/filters.h, app/src/main/jni/main_processing.cpp, app/src/main/res/values/arrays.xml
Fixed https://github.com/fossasia/phimpme-android/issues/1930
**Changes**:
I added fade filter.It creates greyscale image and perform bw contrast.
I changed files from **phimpme-android/app/src/main/jni/** location containing filters.cpp   ,filters.h , main_processing.cpp and an array file from **app/src/main/res/values/arrays.xml** .
**Screenshots for the change**:
**Before** 
**After**
=> Fixed #1930 Added Fade Filter

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fixed #1928 
Changes: Changed the exit reveal with start reveal for a better animation.
Changes can be seen from the following video: 
https://drive.google.com/open?id=1Mrtp16ZXgHlHKJC9DKVzuY92GaDj-yxC
=> Fixed the circle reveal animation on top bar.

README.md
Fixed #1793 
Changes: Corrected Grammatical Error in README.
=> Fixes the Grammatical Error.

README.md
Fixed #1962 
Changes: Removed grammatical errors from README.md
=> Correcting grammatical errors in README.md

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/SnackBarHandler.java, app/src/main/res/values/strings.xml
Fixed #1997 
Changes: Option to directly open favorites collection from the snackbar message(message displayed after the successful operation of adding images to the favorites collection).
=> Fix #1997-Add to favourites feature enhancement.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java, app/src/main/res/layout/dialog_security_folder.xml
Fixed #1776 
Changes: The dialog button and title background color change
according to the change in the Accent color.
=> Choose folders to secure dialog issue fixed.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/adapters/MediaAdapter.java, app/src/main/res/layout/card_photo.xml, app/src/main/res/menu/menu_bottom_view_pager.xml
Fixed #1990 
Changes: Yellow colored star mark no longer appears in the photos item view for fav marked photos, the heart icon in the SingleMediaActivity appears color marked(Accent color) for the photos added to the fav collection.
gif before change:
gif after change:
=> Photos item view modified

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/util/ThemeHelper.java, app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java, app/src/main/res/layout/activity_leafpic.xml
Fixed #2014 
Changes: On deleting an image from upload history via the SingleMediaActivity, the image is deleted from the upload history list and rest of the images are displayed properly.
=> Fix #2014 - Upload history item delete issue fixed.

app/src/main/java/org/fossasia/phimpme/accounts/AccountAdapter.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/drawable/ic_delete_sweep_black_24dp.xml, app/src/main/res/layout/trashbin_empty_view.xml, app/src/main/res/menu/menu_view_pager.xml
Changes: Merging development to master.
=> Merging development to master.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java, app/src/main/res/layout/upload_history_activity.xml
Fixed #2068 
Changes: Unexpected behavior while deleting the only item present in the Upload History section resolved.
Empty view display issue fixed for Upload History section.
GIF displaying the change:
=> Fix #2068-Upload history single media delete issue fixed.

app/src/main/res/layout/upload_history_activity.xml, app/src/main/res/values/dimens.xml
Fixed #2054 
Changes: Size of the empty icon reduced.
=> Fix #2054-Size of the empty icon reduced.

app/src/main/res/drawable/ic_more_vert_black_24dp.xml, app/src/main/res/layout/trashbin_item_view.xml, app/src/main/res/layout/upload_history_item_view.xml, app/src/main/res/menu/menu_popup_trashbin.xml, app/src/main/res/values/strings.xml
Fourth step for #2041 
Changes: Added trash bin display object item view.
=> Added TrashBin object item view.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fixed #2087 
Changes: App crash fixed for all photos section photo click operation.
=> Fix #2087-Fixed crash for all photos section.

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/share/twitter/AppConstant.java, app/src/main/java/org/fossasia/phimpme/share/twitter/LoginActivity.java
Fixed #2088 
Changes: According to a recent change made by Twitter, the twitter call back URL in the code must be exactly same as that of the one mentioned on the Twitter developer console for the app, which was not the case few months back. As the change was not done in the code, the authentication part was not working. Therefore made necessary changes. Added a onBackPress method for performing abort operation while running the authentication operation.
=> Fix #2088-Twitter authentication issue fixed.

app/src/main/java/org/fossasia/phimpme/editor/CompressImageActivity.java
Fixed #2091 
Changes: When compress operation is performed on any image, the resultant compressed version is saved in a folder named "Phimpme-compress"  and the folder is displayed at the top in the albums view.
=> Fix #2091-Compress operation display issue fixed.

app/src/main/jni/filters.cpp, app/src/main/jni/filters.h, app/src/main/jni/main_processing.cpp, app/src/main/res/values/arrays.xml
Fixed #2085 
Changes: Added a whitish-yellow tint color filter.
The filter preview:
=> Fix #2085-Added a whitish-yellow tint color filter.

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java, app/src/main/res/menu/menu_uploadhistoryactivity.xml, app/src/main/res/values/strings.xml
Fixed #2067 
Changes: Added delete option in the upload history section to delete/clear all the items at once.
=> Fix #2067-Added option to clear upload history section at once.

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/util/AlertDialogsHelper.java, app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java, app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinAdapter.java, app/src/main/java/org/fossasia/phimpme/trashbin/TrashDiffCallback.java, app/src/main/res/drawable/ic_delete_sweep_black_24dp.xml, app/src/main/res/layout/activity_drawer.xml, app/src/main/res/layout/activity_trash_bin2.xml, app/src/main/res/layout/dialog_checkbox.xml, app/src/main/res/layout/trashbin_item_view.xml, app/src/main/res/values/strings.xml
Fifth step for #2041 
Changes: The Trash Bin section containing the deleted images would be displayed separately from the other albums just as the favorite section.
GIF for the implementation:
=> Trashbin UI display.

app/src/main/java/org/fossasia/phimpme/accounts/CloudRailServices.java, app/src/main/java/org/fossasia/phimpme/editor/CompressImageActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fixed #2080
Changes: Fixed app crash for compressing images from compress folder.
=> Fix #2080-App crash for compress action fixed.

app/src/main/java/org/fossasia/phimpme/editor/CompressImageActivity.java, app/src/main/res/layout/activity_compress_image.xml, app/src/main/res/layout/dialog_compresspixel.xml, app/src/main/res/layout/dialog_compresssize.xml, app/src/main/res/values/strings.xml
Fixed #2078 
Changes: Compress option dialog issue fixed. The button colors, title background, seekbar's color changes according to the change in accent and primary colors.
=> Fix #2078-Compress option dialog issue fixed.

app/build.gradle, build.gradle
Changes: Fixed two unsecure URLs in the gradle file(Security error was occurring in the Fdroid build process).
=> Minor gradle update for security purpose.

README.md
Changes: Merging changes from development.
=> Merging changes from development

app/src/main/java/org/fossasia/phimpme/utilities/Constants.java
Changes: Added sharing api keys for master.
=> Added sharing api keys for master

app/src/main/java/org/fossasia/phimpme/editor/fragment/FrameFragment.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java, app/src/main/res/values/strings.xml
Fixed #2133 
Changes: Added material design icon for the cancel button in Frames section.
Modified the empty message of favorites section.
Modified the checkbox tint of password security dialog(SecurityActivity).
=> Fix #2133-Issues in the EditActivity, Favourites section resolved.

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/SnackBarHandler.java
Final step for #2124 
Changes: Implemented undo option for copy and move operation.
=> Part of #2124-Implemented undo option for copy and move operation.

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/MyApplication.java, app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/adapters/AlbumsAdapter.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/share/nextcloud/IndeterminateProgressDialog.java, app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinAdapter.java, app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistoryAdapter.java, app/src/main/res/values/styles.xml
Changes: Removed FB-Sdk from the project.
=> Part of #2119 - Removed FB-Sdk for Froid merge request.

app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java, app/src/main/res/menu/menu_trashbin.xml, app/src/main/res/values/strings.xml
Part of #2125 
Changes: Implemented option to restore all the trashbin photos at once.
=> Restore all at once.

app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java, app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinAdapter.java
Part of the issue #2041 
Changes: Added permanent delete functionality in the Trashbin section.
=> Permanent delete option for Trashbin photos.

app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java, app/src/main/res/menu/menu_trashbin.xml, app/src/main/res/values/strings.xml
Part of #2125 
Changes: Implemented option to clear Trashbin at once.
=> Part of #2125-Implemented option to clear Trashbin at once.

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/SnackBarHandler.java
Part of #2124 
Changes: Implemented Undo operation for Delete functionality.
=> Part of #2124-Implemented Undo operation for Delete functionality.

app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java, app/src/main/res/drawable/ic_delete_sweep_white_24dp.xml, app/src/main/res/layout/activity_trash_bin2.xml
Fixed #2136
Changes: The empty icon and the color of the text message changes according to the change in theme.
=> Fix #2136-trashbin emptyview set according to the base theme.

app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinAdapter.java
Part of issue #2041 
Changes: Added option to restore photo from the Trashbin.
=> Implemented restore photo option in the trashbin section.

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java, app/src/main/res/menu/menu_albums.xml
Changes: Adding the latest changes into master.
=> Merging development into master

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/adapters/ImageAdapter.java
Fixed #[1681]
Changes: [I have changed ImageAdapter and SingleMediaActivity in order to solve the issue]
Problem : I think through my tests on codes at first time when a viewHolder created and bind the data to it by adapter then it listen for all of it's listener and when we swipe it then again it bind new data but when we go back adapter position is not updated so all the listener for old position is not working so when we go to 3 position it will not listen for position 1 and 2.
=> Fix for issue onSingleTap stops working 

app/src/main/res/layout-land/fragment_editor_main.xml
Fixed #2164 
Changes: The fragment_editor_main.xml file (layout-land file)  for editor activity did not contain an entire view for frames. So i added the frames layout in the file thus preventing Null Pointer Exception given by findViewById() which was accessed by the corresponding JAVA file.
=> Fixed#2164 App does not crash in landscape mode in Editor Activity

photoview/src/main/java/uk/co/senab/photoview/PhotoView.java
Fixed #1635 
Changes: [make update in photoview module in order to retain it's original state when system flag is called so in order to do this i need to make call the update method in get matrix method and also added the condition that it's only update when changed is applied.]
=> Fix #1635 (image is automatically zoomed out when systemUI gets hidden in SingleMediaActivity)

app/src/main/java/org/fossasia/phimpme/editor/fragment/FrameFragment.java
Fixed #2177 
Changes: [When phone orientation changes layout should also changes it orientation so in order to do this i added a condition in FrameFragment for changing the orientation. ]
=> Fix #2177 List should be orientation dependent (Frame section)

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fixed #2180 
Changes: [when clicking on the first image of the album it's not calling the OnPageChangeListener that's why it's button not getting updated so i added below code to change it's color when it's in the favorite list.]
=> Fix #2180 (Favorite button color is not changed after adding it to the favorite list)

app/src/main/java/org/fossasia/phimpme/editor/view/StickerItem.java
Fixed #2195 
Changes: [I changes it position for rendering the stickers on stickerview (on image) and i prefer to use random position for stickers so that they don't shows as this issue states.]
=> Fix #2195 (Tap on sticker creates stickers at the same place)

app/src/main/AndroidManifest.xml
The app now supports landscape orientation for AccountActivity.
Fixed #2216 
Changes: AndroidManifest.xml
=> Fixes #2216 Landscape orientation for AccountActivity

app/src/main/res/layout-land/fragment_edit_image_add_text.xml
Fixed #2191 
Changes: The layout of the landscape file was missing the text_font button which caused the null pointer exception. So i added the button
=> Fixed#2191 App does not crash on clicking add text

app/src/main/java/org/fossasia/phimpme/gallery/activities/AboutActivity.java, app/src/main/res/values/strings.xml
Fixed #2225 : Website opens through chrome custom tabs
Changes: Launched the url through chrome custom tabs
=> fix#2225: Website opens through custom tab

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fixed #2235 
Changes: Only jpeg files were being added to path so i improved the if condition which checked which files go into the path
=> Fixed#2235 Zip Issue Fixed

app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/utilities/Utils.java
Fixed #2237 
Changes: Added function which sends the image to messenger via intent.
=> Fixed#2237  Messenger button works

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/res/menu/menu_albums.xml, app/src/main/res/values/strings.xml
Fixed #2242 
Changes: Created a new Async Task that creates a zip file for selected Images and saves in a folder called Phimpme Zips.
=> Created a new Async task that creates zip for images

app/src/main/res/drawable/ic_search_white_24dp.xml, app/src/main/res/menu/menu_albums.xml
Fixed #2310 
Changes: set showAsAction attribute to "always|collapseActionView"
=> fix: SearchView hides other menu items

app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java, app/src/main/res/layout/activity_trash_bin2.xml
Fixed #2313 
Changes: The Trash Bin icon will change color when the primary color is changed from settings. Text views have been modified slightly to improve the UI,
=> feat: Improve UI of empty Trash Bin

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fixed #2221
Changes: LFMainActivity.java
=> Fixed #2221: Close search bar on back pressed

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fixed #2326
Changes: restoring images ffrom trash bin does not require password now.
=> restoring images from trashbin does not require password

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/values/strings.xml
Fixed #2348 
Changes: 
cancel button was added.
ok button was disabled until no input was given.
a toast was added to ensure the user that slideshow has started.
=> slideshow feature improved

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/values/strings.xml
Fixed #2351 
Changes: 
maximum time duration was set to 10 sec and a toast was added.
=> slideshow maximum duration was set to 10 sec

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/MyApplicationInterface.java, build.gradle, openCVLibrary24133/build.gradle, photoview/build.gradle
Changes: Updated app version details and gradle sdk configuration for playstore release.
=> Gradle configuration changes for playstore update.

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fixed #2365 
Changes: If security is on for local folders, the password will be asked to view all photos.
=> Fix for issue#2365 : A password is asked to view all photos if security is active.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java, app/src/main/res/layout/dialog_password.xml, app/src/main/res/layout/dialog_set_password.xml, app/src/main/res/values/strings.xml
Fixed #2354 
Changes: Passwords now have upto 128 characters.
=> Fix for issue#2354 : Password length can now be upto 128 characters.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java, app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java, app/src/main/res/layout/activity_drawer.xml, app/src/main/res/values/strings.xml
Fixed #2240 
Changes: Went through the entire code base and replaces hard coded strings with string resource.
=> Fix #2240 - Replaced hardcoded strings with string resources.

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/data/HandlingAlbums.java
Fixed #2410 
Changes: Files changes: LFMainActivity.java, HandlingAlbums.java. Fixed bug where LongPressinging didn't select albums properly.
Screenshots:
=> Fix #2410 Albums get selected properly.

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java, app/src/main/java/org/fossasia/phimpme/opencamera/Preview/Preview.java, app/src/main/java/org/fossasia/phimpme/opencamera/UI/FolderChooserDialog.java
Fixed #2384 
Changes: Toasts have been replaced with SnackBars wherever a SnackBar is more appropriate than a Toast.
Some of the screenshots of the change are :
=> Fix for issue#2384: Replaced Toasts with SnackBars.

app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java, app/src/main/res/values/strings.xml
Fixed #2449 
Changes: 
dialog button color set to accent color.
a hard-corded string was added to strings.xml
=> forgot password dialog button change as per accent color

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
Fixed #2463 
Changes: 
redundant snackbar from accounts activity removed.
snackbar of shareToImgur replaced with a toast.
=> fix #2463: multiple snackbar issue fixed.

app/src/main/res/layout/activity_settings.xml, app/src/main/res/layout/activity_wordpress_login.xml, app/src/main/res/layout/dialog_affix.xml, app/src/main/res/layout/dialog_explorer.xml, app/src/main/res/layout/dialog_map_provider.xml, app/src/main/res/layout/dialog_media_viewer_theme.xml, app/src/main/res/layout/dialog_progress.xml, app/src/main/res/layout/dialog_security_folder.xml, app/src/main/res/layout/dialog_set_password.xml, app/src/main/res/layout/image_description.xml, app/src/main/res/layout/secure_folder_dialog_item_view.xml, app/src/main/res/layout/share_item_view.xml, app/src/main/res/values/strings.xml
Fixed #2484 
Changes: Hardcoded strings in xml files have with replaced with string resource values.
=> Fix for issue#2484: Removed hardcoded strings from xml files.

app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistory.java, app/src/main/res/menu/menu_uploadhistoryactivity.xml
Fixed #2500 
Changes: 
Settings added to the overflow menu of upload history folder.
=> added settings to the overflow menu of upload history

app/src/main/jni/filters.cpp, app/src/main/jni/filters.h, app/src/main/jni/main_processing.cpp, app/src/main/res/values/arrays.xml
**New Feature**
Add a filter to the app that gives an oil painting effect to the image
**Screenshot:**
=> added oil painting filter

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fixed #2498 
Changes: 
password feature removed from favorite and upload history while deleting some media.
=> removed password from favourite and upload history

app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java, app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinAdapter.java
Fixed #2329 
Changes: [add the dialog and method to handle the delete in trash bin.]
=> Fix #2329 permanent delete option issue trash bin

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java
Fixed #2255
Changes: App now accesses the previous password when password is set up again. Also the user can  always change the password if he wants to.
=> Fixed#2255 App now accesses the previous password when password is set up again

app/src/main/res/values/strings.xml
Fixed #2613 
Changes: 
typo in multi column sub text fixed.
=> typo fixed

app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java, app/src/main/res/layout/dialog_media_viewer_theme.xml
Fixed #2479 
Changes: Removed the unused icon which was taking up unnecessary space.
=> Fix for issue#2479: Fixed the unneccesary gap

app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java
Fixed #2544 
Changes: The color of show password checkbox changes with a change in accent color.
=> Fix for issue#2544: Made the checkbox color change with change in accent color.

app/build.gradle
Fixed #2666 
Changes: Fixed the failing Travis build.
=> fix: Travis build fixed.

app/src/main/java/org/fossasia/phimpme/MyApplication.java, app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/AddTextFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/RecyclerMenuFragment.java, app/src/main/java/org/fossasia/phimpme/editor/view/StickerItem.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/HDRProcessorException.java, app/src/main/java/org/fossasia/phimpme/opencamera/Camera/ImageSaver.java, app/src/main/java/org/fossasia/phimpme/opencamera/Preview/CameraSurface/CameraSurface.java, app/src/main/java/org/fossasia/phimpme/opencamera/Preview/Preview.java, app/src/main/java/org/fossasia/phimpme/opencamera/UI/DrawPreview.java, app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java, app/src/main/java/org/fossasia/phimpme/share/twitter/AppConstant.java, app/src/main/java/org/fossasia/phimpme/uploadhistory/UploadHistoryAdapter.java, app/src/main/java/org/fossasia/phimpme/utilities/Constants.java
Fixed #2643 
Changes:
the variables which had no usage in any place were removed.
some of the string constant variable were commented out for future use.
=> removed unsed variables

app/src/main/res/layout/activity_security_layout.xml
Fixed #2554 
Changes: added the scrollView to view all component.
=> Fix #2554 Text and radio button is hidden when changing the orientation

app/src/main/java/org/fossasia/phimpme/gallery/activities/AboutActivity.java, app/src/main/java/org/fossasia/phimpme/trashbin/TrashBinActivity.java, app/src/main/res/menu/menu_about.xml, app/src/main/res/menu/menu_trashbin.xml
Fixed #2501 
Changes: Settings has been added to overflow menus in about and trashbin activities.
=> Fix for issue#2501: Added overflow menu to trash bin and about activities.

README.md
Fixed #2584 
Changes: Position of developer's images is now positioned in the center of their respective columns.
=> fix: Fixed the position of developer's images in README.md

app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java
Fixed #2507 
Changes: Now even if the screen is rotated, password is visible when show password is checked.
=> Password is now visible everytime when show password is checked.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/values/strings.xml
Fixed #2532 
Changes: Now an alert dialog is shown if the user adds "." while renaming the image.
=> Fixes issue#2532: Placed a warning dialog if user adds a "." in the file name while renaming.

app/src/main/java/org/fossasia/phimpme/base/BaseActivity.java
Fixed #2652 
Changes: showing instruction showcase when read external storage permission in provided instead of write external storage
=> changed condition to start showcase in base activity

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fixed #2519 
Changes: [I have already work on this issue in #2226 so that same method call on the activity and that it's not hidden all time]
=> Fix #2519 actionbar hidden

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fixed #2568 
Changes: [add click on cancel button and perform the click on local folder section in the navigation drawer.]
=> Fix #2568 Title of the Toolbar has change and navigation section also but not the content 

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/values/strings.xml
Fixed #2685 
Changes:
removed unnecessary else if statements and the strings related to it.
=> removed unnecessary else if statements and the strings related to it.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/menu/menu_view_pager.xml, app/src/main/res/values/strings.xml
Fixed #2718 
Changes: An option has been added which uses the same function as printing but directly tells the user that the feature can be used to convert an image to pdf and save the image as pdf.
=> fix: Added a convert to PDF option.

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fixed #2709 
Changes: Text is now visible properly in every theme.
=> fix: Fixed color of description text.

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fixed #2711 
Changes: [There is click listener which is calling on same button action which is NEGATIVE button so i changed one of them to positive]
=> Fix #2711 Hidden folder opening issue

README.md
Changes: [Updated Readme.md] 
A lot of new developer face the issue of ndk while setting the project.
=> Build error due to ndk version

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java
Fixed #2726 
Changes: [scroll the recyclerview at top after changing the section.]
=> Fix #2726 same position issue

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/util/CustomNestedView.java, app/src/main/java/org/fossasia/phimpme/gallery/views/CustomScrollBarRecyclerView.java, app/src/main/res/layout/activity_leafpic.xml
Fixed #2510
Changes: [Make custom NestedView and also add method in custom recyclerview in order to handle touch event so that if the content is empty it will not scroll ]
=> Fix #2510 scroll issue in Favorite section

app/src/main/AndroidManifest.xml
Changes: App version in manifest updated to match play store release.
=> chore: App version in manifest updated to match play store release.

app/src/main/java/org/fossasia/phimpme/editor/font/FontPickerDialog.java
Fixed #2672 
Changes: Font dialog now appears better than it was.
=> fix: Dialog appearance improved.

app/src/main/jni/Application.mk, build.gradle, gradle/wrapper/gradle-wrapper.properties
Fixed #2739
Changes: Fixed the travis build.
=> chore: Fixed travis build

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
Fixed #2600
Changes: In all dialogs in which there is an edit text, now on pressing the enter button on keyboard, the same action takes place as on pressing ok button.
=> fix: Made keyboard enter have same action as ok button on dialog.

README.md
Fixed #2762 
Changes: Updated readme with new instructions to build the app.
=> chore: Updated readme with new instructions

.travis.yml
Changes: Fixed the travis script so that build occurs without any error.
=> chore: Fix travis script

app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java, app/src/main/java/org/fossasia/phimpme/editor/CompressImageActivity.java, app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/CropFragment.java, app/src/main/java/org/fossasia/phimpme/editor/fragment/FrameFragment.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/ExcludedAlbumsActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java, app/src/main/java/org/fossasia/phimpme/share/owncloud/OwnCloudActivity.java, app/src/main/res/layout/activity_edit_exif.xml, app/src/main/res/layout/dialog_multi_column.xml, app/src/main/res/values/strings.xml
Fixed #2658 
Changes: Removed hardcoded strings which were present at many places in the app.
=> fix: Removed hardcoded strings from the app

.github/release-drafter.yml
Fixed #2783 
Changes: Added release-drafter.yml to maintain a changelog.
=> chore: Add release-drafter.yml to maintain a changelog

app/build.gradle
Fixed #2792
Changes: Updated app version name and code
=> chore: Updated app version name and code

scripts/update-apk.sh
Fixed #2794 
Changes:  Attempt to fix the update-apk script.
=> fix: Attempt to fix update-apk script

.travis.yml, scripts/prep-key.sh, scripts/update-apk.sh
Fixed #2797 
Fixed #2303 
Changes: Simplifies signing of apk.
=> chore: Updated update-apk script

app/build.gradle, build.gradle
Fixed #2816
Changes: Updated the build.gradle files for the new apk signing process.
=> chore: Updated build.gradle for the new signing process

scripts/update-apk.sh
Fixed #2818
Changes: Changed the bundle name in the update-apk script.
=> fix: Fix the update-apk script

scripts/update-apk.sh
Fixed #2842 
Move to correct directory containg metadata
=> chore: Move to correct directory containg metadata

.travis.yml
Reverts fossasia/phimpme-android#2838
=> Revert "chore: Disable OpenCV download"

app/build.gradle
Fixed #2850 
Removed unused maven dependencies.
=> fix: Remove unused maven dependencies.

.travis.yml, docs/sources/Makefile, docs/sources/conf.py, docs/sources/index.rst, docs/sources/make.bat, scripts/upload-gh-pages.sh
Fixed #2832
Fixed #2252
Changes: Used Sphinx to make travis generate a website automatically.
=> feat: Generate gh-pages from travis.

README.md
Fixed #2861 
Changes: Corrected the path of staticlibs folder.
=> chore(docs): Corrected the path of staticlibs folder

app/src/main/res/layout-land/fragment_edit_paint.xml, app/src/main/res/layout-land/fragment_editor_frames.xml, app/src/main/res/layout-land/fragment_editor_recycler.xml, app/src/main/res/layout-land/fragment_editor_stickers.xml, app/src/main/res/layout/activity_excluded.xml, app/src/main/res/layout/activity_next_cloud_auth.xml, app/src/main/res/layout/activity_preview.xml, app/src/main/res/layout/fragment_edit_paint.xml
Fixed #2878 : Replaced usage of support library to android x
Changes: Replaced usage of support library to android x
=> fix: Replaced usage of support library to android x

app/build.gradle
Fixed #2882 
Changes: dependency upgrade to 5.0.0
=> chore(deps): upgraded box dependency to 5.0.0

app/src/main/res/values/styles.xml
Fixed #2899 
Changes: Changed theme to android:theme
=> fix: theme in toolbar style

app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java, app/src/main/res/layout/activity_pager.xml
Fixed #2644 
Changes: removed the hardcoded margin with layout view height logic
@yashk2000 Please review
=> fix: Margin of snackbar in single media activity

app/build.gradle, app/src/main/java/org/fossasia/phimpme/MyApplication.java
Fixed #2910 
Changes: Removed stetho dependency
=> fix: removed stetho dependency

app/build.gradle
Fixed #2912 
Changes:
Increment versioname and code
=> chore: Version name changed to 1.10.0

app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/adapters/AlbumsAdapter.java, app/src/main/res/layout/card_album.xml, app/src/main/res/values/dimens.xml
Fixed #2931 
Changes: 
- Follows android standard gallery 
- Font size and style set to normal
- Layout hierarchy changed to Constraint and simple one
- UI improved
Before Screenshot
=> fix: albums view acc to gallery standard

build.gradle
Fixed #2943 
Changes: removed stetho dependency from build.gradle
=> fix:removed stetho dependency from build.gradle

app/src/main/AndroidManifest.xml
Fixed #2953 
Changes: Made the app id the same in the Manifest file as it is there in Constant.java
=> fix: Pinterest issue in Account

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/phimpme/base/ThemedActivity.java, app/src/main/java/org/fossasia/phimpme/gallery/data/providers/MediaStoreProvider.java
fixes inflate crash by removing `IconicsContextWrapper`, it's deprecated anyway
Also fixes #2982
fixes #2927
=> fix: inflate crash and media provider bug
